// <auto-generated />
namespace Fly01.Faturamento.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NfeFcp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NfeFcp));
        
        string IMigrationMetadata.Id
        {
            get { return "201804171734392_NfeFcp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
