// <auto-generated />
namespace Fly01.Faturamento.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alter_OrdemVenda_ImpostosNaoIncidentes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alter_OrdemVenda_ImpostosNaoIncidentes));
        
        string IMigrationMetadata.Id
        {
            get { return "201804091426380_Alter_OrdemVenda_ImpostosNaoIncidentes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
