// <auto-generated />
namespace Fly01.Faturamento.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_EnquadramentoLegalIPI_Descricao_MaxLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_EnquadramentoLegalIPI_Descricao_MaxLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201803241950440_update_EnquadramentoLegalIPI_Descricao_MaxLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
