using Fly01.Financeiro.DAL.Migrations.DataInitializer.Contract;
using System;
using System.Linq;
using System.Data.Entity.Migrations;
using Fly01.Financeiro.API.Models.DAL;
using Fly01.Core.Entities.Domains.Commons;

namespace Fly01.Financeiro.DAL.Migrations.DataInitializer
{
    public class BancoDataInitializer : IDataInitializer
    {
        public void Initialize(AppDataContext context)
        {
            if (!context.Bancos.Any())
            {
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("0B7ED23D-ABFC-417E-ADDB-000C19857E66"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "654", Nome = "BANCO A.J.RENNER S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("5D13FB04-9028-4435-B54F-02D20B4DE929"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "025", Nome = "BANCO ALFA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("2F50A2E9-C682-41F5-A0C2-054A5B8FCE2E"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "641", Nome = "BANCO ALVORADA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("7DAAD2A6-57FE-401E-805D-0660552A2F8E"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "246", Nome = "BANCO ABC BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("A83C24B6-76E9-41BF-8B79-0B373A2F74BC"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "213", Nome = "BANCO ARBI S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("80CB534B-44C4-4B3B-AF6F-0D905735B213"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "019", Nome = "BANCO AZTECA DO BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("E286A869-9A6F-45AD-A557-0DCDAD406828"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "029", Nome = "BANCO BANERJ S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("D129A733-2B78-4C97-B619-1423E84F91AA"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "000", Nome = "BANCO BANKPAR S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("77B507A8-B475-4D84-91F8-154F632E0FCF"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "740", Nome = "BANCO BARCLAYS S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("8CB4DC69-7C61-4D27-9311-159028FBBDE0"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "107", Nome = "BANCO BBM S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("4F244E4E-8E7A-46F5-9397-15D5AA49E31C"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "031", Nome = "BANCO BEG S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("0F8C0D7C-8C4F-45E9-82A1-168F12F82265"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "739", Nome = "BANCO BGN S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("ADAFFFD3-E0F1-4684-8389-19197DC428B5"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "096", Nome = "BANCO BM&F DE SERVICOS DE LIQUIDACAO E C" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("B606D5F0-82D5-49EC-B18E-198FC990D3B1"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "318", Nome = "BANCO BMG S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("9C828153-7838-4700-92D0-1A27B456F5CB"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "752", Nome = "BANCO BNP PARIBAS BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("A92FB385-FA7F-4526-A0F5-1DD8FD3E1DD5"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "248", Nome = "BANCO BOAVISTA INTERATLANTICO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("19FBBB13-A5A4-4355-8592-1DE7145BC392"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "218", Nome = "BANCO BONSUCESSO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("560443D4-72C3-4B45-8528-203312473A1B"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "065", Nome = "BANCO BRACCE S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("8599A63E-3A46-4730-B484-214C33CE795F"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "036", Nome = "BANCO BRADESCO BBI S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("1743F1FC-47D2-4EF3-A607-22843FB894F1"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "204", Nome = "BANCO BRADESCO CARTOES S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("0017402D-0760-49D8-AB31-24A54B9ACBC4"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "394", Nome = "BANCO BRADESCO FINANCIAMENTOS S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("17D335B9-29B4-4FE1-AAE9-27165C85C7C3"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "237", Nome = "BANCO BRADESCO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("2AC903DA-0409-470D-9439-2875CCCA6BDD"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "225", Nome = "BANCO BRASCAN S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("BF534C1C-D21B-44DC-B688-29F1E0D2CD14"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M15", Nome = "BANCO BRJ S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("9EC60C5A-EEEF-47A1-86ED-2BDFCAAF0B3C"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "208", Nome = "BANCO BTG PACTUAL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("344DEBA2-51EB-4FC6-A32F-2C2CDC109597"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "044", Nome = "BANCO BVA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("AE69BC52-50BA-4B1E-BF7D-2C38B0589988"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "263", Nome = "BANCO CACIQUE S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("CAEE46ED-9373-47EA-A980-2C3C37ADAB02"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "473", Nome = "BANCO CAIXA GERAL - BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("658C9F66-6075-4BA3-811A-2D3485945761"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "412", Nome = "BANCO CAPITAL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("87A954A9-A1D6-4EF5-97B0-30152B01798F"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "040", Nome = "BANCO CARGILL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("AA17D505-92FC-4B9D-976C-306E2CFB02CE"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "745", Nome = "BANCO CITIBANK S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("197EC417-E5B3-4A2D-AFD1-345DAFD7B005"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M08", Nome = "BANCO CITICARD S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("6EB82408-E429-411F-BF49-35B9C466D2B9"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "241", Nome = "BANCO CLASSICO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("105C054C-5019-4E27-995A-35E894C2953F"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M19", Nome = "BANCO CNH CAPITAL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("B8A566D5-E3E6-431C-974E-362D0F9F5811"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "215", Nome = "BANCO COMERCIAL E DE INVESTIMENTO SUDAME" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("AD1ED155-1931-491C-B751-3CB07B647A31"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "756", Nome = "BANCO COOPERATIVO DO BRASIL S.A. - BANCO" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("7DDB36BB-71DF-4C0F-B4AC-3DFEB29F80B6"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "748", Nome = "BANCO COOPERATIVO SICREDI S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("A54D1CC5-88A3-4226-BC7B-3E686CA5EF56"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "075", Nome = "BANCO CR2 S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("400920DF-4C06-4903-9277-41398384E127"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "721", Nome = "BANCO CREDIBEL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("7FB4ED9C-F8ED-4546-84AA-447B9102032C"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "222", Nome = "BANCO CREDIT AGRICOLE BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("7B066812-1F15-4798-BC6B-45158D5171EA"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "505", Nome = "BANCO CREDIT SUISSE (BRASIL) S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("B1ED9C33-0E5E-418A-BDA1-463898DA4B75"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "229", Nome = "BANCO CRUZEIRO DO SUL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("00B17349-AFF5-4306-B2B5-479F965B9F50"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "266", Nome = "BANCO CEDULA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("CCF2B4E8-610B-4E59-B3D8-47A68D0F66BC"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "003", Nome = "BANCO DA AMAZONIA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("4B82E9B0-E0A6-4D99-B103-4821456848C8"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "083", Nome = "BANCO DA CHINA BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("30B2DFBA-4342-4DB8-8E45-4BC8ED5B7A18"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M21", Nome = "BANCO DAIMLERCHRYSLER S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("5E5892D4-913F-4A5B-B0BE-4CC050AF08E7"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "707", Nome = "BANCO DAYCOVAL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("C192FEE8-711E-449F-BAAD-4DD071F12CBD"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "300", Nome = "BANCO DE LA NACION ARGENTINA" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("8B508147-E449-485D-A16B-4DD18401096F"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "495", Nome = "BANCO DE LA PROVINCIA DE BUENOS AIRES" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("FCCF141F-5B00-4238-BDB1-50BA6DF3ABFA"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "494", Nome = "BANCO DE LA REPUBLICA ORIENTAL DEL URUGU" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("79BDFB50-F66C-4228-9309-510736A7B95E"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M06", Nome = "BANCO DE LAGE LANDEN BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("FA6E5300-FD2A-4CD6-BA23-511B6ECC821B"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "024", Nome = "BANCO DE PERNAMBUCO S.A. - BANDEPE" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("C9017782-EB2E-4675-B741-51808A39493B"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "456", Nome = "BANCO DE TOKYO-MITSUBISHI UFJ BRASIL S.A" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("F9F435B9-042B-4F7D-B677-521CE6DBADC2"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "214", Nome = "BANCO DIBENS S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("AADE7CFA-9D54-4593-BC0F-52854FDA385F"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "001", Nome = "BANCO DO BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("39401B40-80F4-4580-A861-52DEF94D8070"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "047", Nome = "BANCO DO ESTADO DE SERGIPE S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("86022076-CB15-4842-997F-5552FCA3ABE9"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "037", Nome = "BANCO DO ESTADO DO PARA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("D52A5633-8815-49E5-802E-574ABE21B543"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "039", Nome = "BANCO DO ESTADO DO PIAUÍ S.A. - BEP" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("6217E7F8-C296-40D5-AE27-582559DB9581"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "041", Nome = "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("AA9D59C2-508C-40EF-A0E4-58D15EF83F50"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "004", Nome = "BANCO DO NORDESTE DO BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("A0E3EC2D-440F-4717-BF03-5914D9F492AF"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "265", Nome = "BANCO FATOR S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("A4C45620-6634-402D-A94A-5997D3034E1D"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M03", Nome = "BANCO FIAT S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("74E7A67D-3CA7-4C72-8798-59E0D0717EA2"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "224", Nome = "BANCO FIBRA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("0F492882-801E-4B9F-91D9-5D03DC657576"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "626", Nome = "BANCO FICSA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("417E6B16-195E-455D-9739-5D892EE6F632"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M18", Nome = "BANCO FORD S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("CD7E190A-4A10-44FF-B488-5F56594C56BD"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "233", Nome = "BANCO GE CAPITAL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("F92FDA7E-F0C4-4F92-9931-629AE1CDBCF9"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "734", Nome = "BANCO GERDAU S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("6BA1A784-E201-4568-A508-637C620EBF7E"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M07", Nome = "BANCO GMAC S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("227E1162-176E-42AC-AF90-63C391F24F2E"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "612", Nome = "BANCO GUANABARA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("D6A857AB-B3A5-4FC1-8929-66923AFFD4B9"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M22", Nome = "BANCO HONDA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("0B314C7A-5342-4E89-A3B9-6734799C46B1"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "063", Nome = "BANCO IBI S.A. BANCO MULTIPLO" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("35341696-A6AA-4A8B-9769-68397FA9F58C"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M11", Nome = "BANCO IBM S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("966DD91C-0644-4827-B4DD-6A2CE7DD04D5"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "604", Nome = "BANCO INDUSTRIAL DO BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("35706D4E-5A9D-44B5-9A5D-6AD45BA4C84D"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "320", Nome = "BANCO INDUSTRIAL E COMERCIAL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("AED69F7A-FE98-44B8-902C-6AF48D6FA4BA"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "653", Nome = "BANCO INDUSVAL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("692B79C8-E3CB-4BE9-805F-6DD11C6A9C52"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "630", Nome = "BANCO INTERCAP S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("69857BCF-0339-44A6-A80C-6E0AD2196605"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "077", Nome = "BANCO INTERMEDIUM S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("751C6C76-41ED-478B-A0DF-6E0DF30FDCA3"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "249", Nome = "BANCO INVESTCRED UNIBANCO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("3817073F-1098-4B60-8E3F-6EAE6CED0BD3"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M09", Nome = "BANCO ITAUCRED FINANCIAMENTOS S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("C9EFE808-DAB0-4867-B26A-706993A732FB"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "184", Nome = "BANCO ITAU BBA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("660473F9-7A0C-462F-BCC0-723B6F6A0492"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "479", Nome = "BANCO ITAUBANK S.A" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("A9CD3A1B-F7D1-44B1-A48A-72FF4337D16E"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "376", Nome = "BANCO J. P. MORGAN S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("2B48E0F2-43AA-472F-92DA-7367D747CEC1"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "074", Nome = "BANCO J. SAFRA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("A0F849CA-FE58-4A9A-A463-7481E19A8668"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "217", Nome = "BANCO JOHN DEERE S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("45F68657-E6A2-41D3-9F85-757201967B45"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "076", Nome = "BANCO KDB S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("4CF88084-6317-4440-B037-75BBC80A1ED6"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "757", Nome = "BANCO KEB DO BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("7AA49EDF-9A70-4A8F-BDCB-761068EDF67B"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "600", Nome = "BANCO LUSO BRASILEIRO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("54849258-F754-44B5-9598-762A7D486345"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "212", Nome = "BANCO MATONE S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("6D4A2BAF-ECF9-464D-A31F-7A14629FC420"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M12", Nome = "BANCO MAXINVEST S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("F2377A7C-AB83-4FEC-A75C-7A561A135D80"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "389", Nome = "BANCO MERCANTIL DO BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("29679460-5811-4960-9B89-7A6FDC6CDA39"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "746", Nome = "BANCO MODAL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("4E7184EA-2A0D-45F9-95C4-7E653165C089"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M10", Nome = "BANCO MONEO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("2DDB717A-6687-406F-B9DF-7F9D82B3CCF6"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "738", Nome = "BANCO MORADA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("178B04AB-195F-4435-B3E7-801B366CFD14"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "066", Nome = "BANCO MORGAN STANLEY S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("72A83A86-C241-4CEC-9C3B-86CEDD149F7E"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "243", Nome = "BANCO MAXIMA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("EBD2A91D-E4CC-42C7-B43B-88162856B6FE"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "045", Nome = "BANCO OPPORTUNITY S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("85FFCB83-3515-4A0B-9952-88D58918C38D"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M17", Nome = "BANCO OURINVEST S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("011E9C09-7528-408E-BEB4-8A28A6D2B053"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "623", Nome = "BANCO PANAMERICANO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("FB787E00-605D-4CC2-9532-8A3A1A603C79"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "611", Nome = "BANCO PAULISTA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("9E276BC9-75C5-4676-8A52-91933D5B7DE2"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "613", Nome = "BANCO PECUNIA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("9415FBD6-F2CF-4888-A6B5-91A456D676D4"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "094", Nome = "BANCO PETRA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("CF14D627-B924-427A-ADFC-91B3E519C2DA"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "643", Nome = "BANCO PINE S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("A53F3009-8EC7-4E32-82B5-91F0044CF244"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "724", Nome = "BANCO PORTO SEGURO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("CAE6C8B7-1F9A-428D-BE12-930F3EE322DB"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "735", Nome = "BANCO POTTENCIAL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("8ED73D9E-00E4-4F4C-AEC3-942E30062AF4"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "638", Nome = "BANCO PROSPER S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("DD1DABA7-0615-40BC-A62E-942EE31683BC"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M24", Nome = "BANCO PSA FINANCE BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("3D9856C9-A014-4FE3-90B3-976F66BDBCE7"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "747", Nome = "BANCO RABOBANK INTERNATIONAL BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("90D316A2-4782-4E9C-8881-988D303AC7B6"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "088", Nome = "BANCO RANDON S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("A583E3C0-A53F-44F1-83F2-98982DF1010F"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "356", Nome = "BANCO REAL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("2C560534-B0F6-4E0C-AD0E-9976A4AFF542"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "633", Nome = "BANCO RENDIMENTO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("47B12C14-9A75-4155-BC8C-9C1AB05EA549"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "741", Nome = "BANCO RIBEIRAO PRETO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("4F1D6592-E68C-4928-B227-9EB22A0F442D"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M16", Nome = "BANCO RODOBENS S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("26F90565-679D-4DEA-98E8-9FA288B29D1E"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "072", Nome = "BANCO RURAL MAIS S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("599A3F91-8C0C-4E25-939A-A26487EC000F"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "453", Nome = "BANCO RURAL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("B3470D66-CB34-4E05-9935-A334B1FD9E47"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "422", Nome = "BANCO SAFRA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("03DC0EC4-3A1D-4F06-9141-A33AD29BE393"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "033", Nome = "BANCO SANTANDER (BRASIL) S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("CB32F503-5A71-4479-9C21-A671EDF3BDC7"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "250", Nome = "BANCO SCHAHIN S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("A01E538D-AC63-4E49-AE41-A69D7B49FFC6"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "743", Nome = "BANCO SEMEAR S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("FB37D124-5BA2-4414-9520-A710BA3D8B34"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "749", Nome = "BANCO SIMPLES S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("64B01396-B7EA-4658-A221-A7BDD63F8E6F"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "366", Nome = "BANCO SOCIETE GENERALE BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("707737B0-BB11-4CC7-9407-A8CEC001A875"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "637", Nome = "BANCO SOFISA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("7F692FEF-3743-44EE-B0C9-A9CDF65C3304"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "012", Nome = "BANCO STANDARD DE INVESTIMENTOS S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("BA771D20-864B-45E3-B7D2-ABEE4AFA375F"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "464", Nome = "BANCO SUMITOMO MITSUI BRASILEIRO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("EAC18EB2-42F5-4875-81F7-ACE966F1E3C5"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "082", Nome = "BANCO TOPASIO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("9B4CE7FC-711F-4108-B546-B15963D88664"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M20", Nome = "BANCO TOYOTA DO BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("7669D910-6D86-4ED6-B0B8-B16C75AAB66F"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M13", Nome = "BANCO TRICURY S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("B7218020-B9B7-456E-BFEC-B282234B4FE2"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "634", Nome = "BANCO TRIAULO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("3C073DA5-0471-49D7-97D3-B628A18CC6B0"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M14", Nome = "BANCO VOLKSWAGEN S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("5C8148B9-2EE7-4662-B422-B8D89749DB04"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "M23", Nome = "BANCO VOLVO (BRASIL) S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("B1E34188-DBAE-49D4-B3D0-B9297CD26110"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "655", Nome = "BANCO VOTORANTIM S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("46D9622D-3CD4-406D-ACA7-BA2A226446A7"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "610", Nome = "BANCO VR S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("7CF1E293-0C09-485C-B048-BDB9D3C5BA5D"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "370", Nome = "BANCO WESTLB DO BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("3C80A839-BCFA-41CB-B999-BE6D7F445F5C"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "021", Nome = "BANESTES S.A. BANCO DO ESTADO DO ESPÍRIT" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("2BC871A3-FDF2-43FD-9051-BEF64963169E"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "719", Nome = "BANIF-BANCO INTERNACIONAL DO FUNCHAL (BR" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("3AA95F17-1B85-4D28-9FF0-C007DFA37DD1"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "755", Nome = "BANK OF AMERICA MERRILL LYNCH BANCO MULT" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("B33DFE41-3195-483D-AC3D-C36B9AD6A37B"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "744", Nome = "BANKBOSTON N.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("804D9717-4429-45A7-8205-C44FB54F8124"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "073", Nome = "BB BANCO POPULAR DO BRASIL S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("1A49022B-183E-4BF3-82C3-C5013BBD4C39"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "078", Nome = "BES INVESTIMENTO DO BRASIL S.A.-BANCO DE" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("83301E1A-1602-48A1-8470-C60A758EB23B"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "069", Nome = "BPN BRASIL BANCO MULTIPLO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("EB5709FD-B376-48B3-91CC-C69A2871F6D5"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "070", Nome = "BRB - BANCO DE BRASÍLIA S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("64EF263F-0B63-4D0E-B5ED-C7C39DC75B1A"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "092", Nome = "BRICKELL S.A. CREDITO, FINANCIAMENTO E I" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("EDCA6B53-E0B2-4077-A1F1-C8B5B2ED0C7F"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "104", Nome = "CAIXA ECONOMICA FEDERAL" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("8BD8047A-D963-4FAE-8DC9-CB40CEBF34C8"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "477", Nome = "CITIBANK N.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("DF248369-65F8-4D5B-8589-CB65883D12EE"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "081", Nome = "CONCORDIA BANCO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("59CCF108-733F-4421-8930-CCB0F60D0BD0"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "097", Nome = "COOPERATIVA CENTRAL DE CREDITO NOROESTE " });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("4607816F-6BBF-40C2-A5C2-CD48BD8BCB64"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "085", Nome = "COOPERATIVA CENTRAL DE CREDITO URBANO-CE" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("D51C0824-8AA6-499A-842B-CE712F6106FD"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "099", Nome = "COOPERATIVA CENTRAL DE ECONOMIA E CREDIT" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("EFF60073-B3FD-42F8-8E25-CF4C5FAA96C1"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "090", Nome = "COOPERATIVA CENTRAL DE ECONOMIA E CREDIT" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("D49BEA81-99AB-43B7-AB46-D4E254F9297F"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "089", Nome = "COOPERATIVA DE CREDITO RURAL DA REGIAO D" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("DE0C0BA8-DF84-4B77-9A64-D89FF0BCA502"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "087", Nome = "COOPERATIVA UNICRED CENTRAL SANTA CATARI" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("0CC6510B-E652-4CEC-823F-DA9ED33F7353"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "098", Nome = "CREDICOROL COOPERATIVA DE CREDITO RURAL" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("7ECFA049-F877-4E4A-AE1F-DC04B3E663C9"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "487", Nome = "DEUTSCHE BANK S.A. - BANCO ALEMAO" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("E0756F5B-7CEC-4D15-A906-DC322466741A"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "751", Nome = "DRESDNER BANK BRASIL S.A. - BANCO MULTIP" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("2AB449A8-E840-4E6B-AC51-DD74B3EBE5BE"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "064", Nome = "GOLDMAN SACHS DO BRASIL BANCO MULTIPLO S" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("B722C776-35B4-4387-A07E-DF0D6C45A404"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "062", Nome = "HIPERCARD BANCO MULTIPLO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("C6C1065D-207C-4A1B-BABB-E0CC8C66E7D5"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "399", Nome = "HSBC BANK BRASIL S.A. - BANCO MULTIPLO" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("9051AFC6-B92B-4B24-AA2F-E2A35EC8C3E7"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "168", Nome = "HSBC FINANCE (BRASIL) S.A. - BANCO MULTI" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("A49919CA-9372-43D1-A0B8-E36FF7049C83"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "492", Nome = "ING BANK N.V." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("F84D8075-5A73-466B-B1DC-E4A53D311660"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "652", Nome = "ITAU UNIBANCO HOLDING S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("DE7CD2CB-860D-4A31-9C68-E7DC3566A1AB"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "341", Nome = "ITAU UNIBANCO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("6FF9A4F5-43C4-4386-880B-E7EF9210CE29"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "079", Nome = "JBS BANCO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("14D1E0B7-48F7-4FEF-AAE9-E8877BDA6ECA"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "488", Nome = "JPMORGAN CHASE BANK" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("9FC23864-5334-406C-8895-E94497D33A28"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "014", Nome = "NATIXIS BRASIL S.A. BANCO MULTIPLO" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("0E27D7F5-C2B3-497B-8B45-EADE927AEFF8"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "753", Nome = "NBC BANK BRASIL S.A. - BANCO MULTIPLO" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("5ED404D1-DD26-4AA6-9E94-F158607FD385"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "086", Nome = "OBOE CREDITO FINANCIAMENTO E INVESTIMENT" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("C936D467-F094-4B19-BB62-F2D7CCA3D5E7"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "254", Nome = "PARANA BANCO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("780CB3EE-DD6E-4BAD-AC12-F370CD71C3C7"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "409", Nome = "UNIBANCO - UNIAO DE BANCOS BRASILEIROS S" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("512683EB-8650-466C-A9F8-F7DF4887F5E2"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "230", Nome = "UNICARD BANCO MULTIPLO S.A." });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("DB50161F-D247-4C66-9DBF-F845375A7C39"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "091", Nome = "UNICRED CENTRAL DO RIO GRANDE DO SUL" });
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("7ADA3509-8AC8-490E-A3B1-FB30CB78C0A7"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "084", Nome = "UNICRED NORTE DO PARANA" });

                context.SaveChanges();
            }

            if (!context.Bancos.Any(x => x.Codigo == "999"))
            {
                context.Bancos.AddOrUpdate(new Banco() { Id = Guid.Parse("9153F37A-FF66-45DE-AB76-FFFD5A145D98"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "999", Nome = "Outros" });
                context.SaveChanges();
            }

            if (!context.Bancos.Any(x => x.Codigo == "001"))
            {
                context.Bancos.AddOrUpdate(x => x.Codigo,
                  new Banco() { Id = Guid.Parse("1054AB30-F04F-48DC-83A8-003C9EEE333B"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "001", Nome = "BANCO DO BRASIL S.A." }
                , new Banco() { Id = Guid.Parse("FD92C367-17A8-4058-9F83-004119CAB10C"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "033", Nome = "BANCO SANTANDER (BRASIL) S.A." }
                , new Banco() { Id = Guid.Parse("97FE9B8D-051F-4DAF-BCCD-005C7EF57BF2"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "237", Nome = "BANCO BRADESCO S.A." }
                , new Banco() { Id = Guid.Parse("2D4D9C0D-E85F-460C-8955-005FC47525D4"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "104", Nome = "CAIXA ECONOMICA FEDERAL" }
                , new Banco() { Id = Guid.Parse("D3EE0E84-2E7D-48B3-B5BE-00674E1089D0"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "341", Nome = "ITAU UNIBANCO S.A." }
                , new Banco() { Id = Guid.Parse("401984C9-4762-4F7E-BAC2-006D99147725"), DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true, Codigo = "041", Nome = "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A" });

                context.SaveChanges();
            }
        }
    }
}