//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly01.EmissaoNFE.API.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://POAD040100155:8080/SPEDADM.apw")]
        public string Fly01_EmissaoNFE_API_SPEDADM_SPEDADM {
            get {
                return ((string)(this["Fly01_EmissaoNFE_API_SPEDADM_SPEDADM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://POAD040100155:8080/SPEDCFGNFE.apw")]
        public string Fly01_EmissaoNFE_API_SPEDCFGNFE_SPEDCFGNFE {
            get {
                return ((string)(this["Fly01_EmissaoNFE_API_SPEDCFGNFE_SPEDCFGNFE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://poad040100155:8080/NFESBRA.apw")]
        public string Fly01_EmissaoNFE_API_NFESBRA_NFESBRA {
            get {
                return ((string)(this["Fly01_EmissaoNFE_API_NFESBRA_NFESBRA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sped.homologacao.totvs.com.br:8087/nfe/NFESBRA.apw")]
        public string Fly01_EmissaoNFE_API_NFESBRAProd_NFESBRA {
            get {
                return ((string)(this["Fly01_EmissaoNFE_API_NFESBRAProd_NFESBRA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sped.homologacao.totvs.com.br:8087/nfe/SPEDADM.apw")]
        public string Fly01_EmissaoNFE_API_SPEDADMProd_SPEDADM {
            get {
                return ((string)(this["Fly01_EmissaoNFE_API_SPEDADMProd_SPEDADM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sped.homologacao.totvs.com.br:8087/nfe/SPEDCFGNFE.apw")]
        public string Fly01_EmissaoNFE_API_SPEDCFGNFEProd_SPEDCFGNFE {
            get {
                return ((string)(this["Fly01_EmissaoNFE_API_SPEDCFGNFEProd_SPEDCFGNFE"]));
            }
        }
    }
}
