//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Fly01.Core.SOAManager.SOAManager
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISOAManager", Namespace="http://tempuri.org/")]
    public partial class SOAManager : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecuteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceNamesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServicesInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivateUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SOAManager() {
            this.Url = global::Fly01.Core.SOAManager.Properties.Settings.Default.Fly01_Utils_SOAManager_SOAManager_SOAManager;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteCompletedEventHandler ExecuteCompleted;
        
        /// <remarks/>
        public event GetServiceCompletedEventHandler GetServiceCompleted;
        
        /// <remarks/>
        public event GetServiceNamesCompletedEventHandler GetServiceNamesCompleted;
        
        /// <remarks/>
        public event GetServiceTypesCompletedEventHandler GetServiceTypesCompleted;
        
        /// <remarks/>
        public event GetServicesInfoCompletedEventHandler GetServicesInfoCompleted;
        
        /// <remarks/>
        public event CreateUserCompletedEventHandler CreateUserCompleted;
        
        /// <remarks/>
        public event ActivateUserCompletedEventHandler ActivateUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Execute", RequestElementName="SOAManagerExecuteRequest", RequestNamespace="http://TotvsSOA.ServiceContracts/v1", ResponseElementName="SOAManagerExecuteResult", ResponseNamespace="http://TotvsSOA.ServiceContracts/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Execute([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SOAConnectionData ConnectionData, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref SOAServiceData ServiceData, bool DebugMode, [System.Xml.Serialization.XmlIgnoreAttribute()] bool DebugModeSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ClientAddress, out SOAResultType ResultType, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ResultTypeSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string ResultMessage, out int ResultMessageCode, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ResultMessageCodeSpecified) {
            object[] results = this.Invoke("Execute", new object[] {
                        ConnectionData,
                        ServiceData,
                        DebugMode,
                        DebugModeSpecified,
                        ClientAddress});
            ServiceData = ((SOAServiceData)(results[0]));
            ResultType = ((SOAResultType)(results[1]));
            ResultTypeSpecified = ((bool)(results[2]));
            ResultMessage = ((string)(results[3]));
            ResultMessageCode = ((int)(results[4]));
            ResultMessageCodeSpecified = ((bool)(results[5]));
        }
        
        /// <remarks/>
        public void ExecuteAsync(SOAConnectionData ConnectionData, SOAServiceData ServiceData, bool DebugMode, bool DebugModeSpecified, string ClientAddress) {
            this.ExecuteAsync(ConnectionData, ServiceData, DebugMode, DebugModeSpecified, ClientAddress, null);
        }
        
        /// <remarks/>
        public void ExecuteAsync(SOAConnectionData ConnectionData, SOAServiceData ServiceData, bool DebugMode, bool DebugModeSpecified, string ClientAddress, object userState) {
            if ((this.ExecuteOperationCompleted == null)) {
                this.ExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteOperationCompleted);
            }
            this.InvokeAsync("Execute", new object[] {
                        ConnectionData,
                        ServiceData,
                        DebugMode,
                        DebugModeSpecified,
                        ClientAddress}, this.ExecuteOperationCompleted, userState);
        }
        
        private void OnExecuteOperationCompleted(object arg) {
            if ((this.ExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteCompleted(this, new ExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetService", RequestElementName="SOAManagerGetServiceRequest", RequestNamespace="http://TotvsSOA.ServiceContracts/v1", ResponseElementName="SOAManagerGetServiceResult", ResponseNamespace="http://TotvsSOA.ServiceContracts/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ServiceData", IsNullable=true)]
        public SOAServiceData GetService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SOAConnectionData ConnectionData, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ServiceType, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ServiceName, int ServiceVersion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ServiceVersionSpecified) {
            object[] results = this.Invoke("GetService", new object[] {
                        ConnectionData,
                        ServiceType,
                        ServiceName,
                        ServiceVersion,
                        ServiceVersionSpecified});
            return ((SOAServiceData)(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceAsync(SOAConnectionData ConnectionData, string ServiceType, string ServiceName, int ServiceVersion, bool ServiceVersionSpecified) {
            this.GetServiceAsync(ConnectionData, ServiceType, ServiceName, ServiceVersion, ServiceVersionSpecified, null);
        }
        
        /// <remarks/>
        public void GetServiceAsync(SOAConnectionData ConnectionData, string ServiceType, string ServiceName, int ServiceVersion, bool ServiceVersionSpecified, object userState) {
            if ((this.GetServiceOperationCompleted == null)) {
                this.GetServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceOperationCompleted);
            }
            this.InvokeAsync("GetService", new object[] {
                        ConnectionData,
                        ServiceType,
                        ServiceName,
                        ServiceVersion,
                        ServiceVersionSpecified}, this.GetServiceOperationCompleted, userState);
        }
        
        private void OnGetServiceOperationCompleted(object arg) {
            if ((this.GetServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceCompleted(this, new GetServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetServiceNames", RequestElementName="SOAManagerGetServiceNamesRequest", RequestNamespace="http://TotvsSOA.ServiceContracts/v1", ResponseElementName="SOAManagerGetServiceNamesResult", ResponseNamespace="http://TotvsSOA.ServiceContracts/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ServiceNames", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetServiceNames([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SOAConnectionData ConnectionData, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ServiceType) {
            object[] results = this.Invoke("GetServiceNames", new object[] {
                        ConnectionData,
                        ServiceType});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceNamesAsync(SOAConnectionData ConnectionData, string ServiceType) {
            this.GetServiceNamesAsync(ConnectionData, ServiceType, null);
        }
        
        /// <remarks/>
        public void GetServiceNamesAsync(SOAConnectionData ConnectionData, string ServiceType, object userState) {
            if ((this.GetServiceNamesOperationCompleted == null)) {
                this.GetServiceNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceNamesOperationCompleted);
            }
            this.InvokeAsync("GetServiceNames", new object[] {
                        ConnectionData,
                        ServiceType}, this.GetServiceNamesOperationCompleted, userState);
        }
        
        private void OnGetServiceNamesOperationCompleted(object arg) {
            if ((this.GetServiceNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceNamesCompleted(this, new GetServiceNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetServiceTypes", RequestElementName="SOAManagerGetServiceTypesRequest", RequestNamespace="http://TotvsSOA.ServiceContracts/v1", ResponseElementName="SOAManagerGetServiceTypesResult", ResponseNamespace="http://TotvsSOA.ServiceContracts/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ServiceTypes", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetServiceTypes([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SOAConnectionData ConnectionData) {
            object[] results = this.Invoke("GetServiceTypes", new object[] {
                        ConnectionData});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceTypesAsync(SOAConnectionData ConnectionData) {
            this.GetServiceTypesAsync(ConnectionData, null);
        }
        
        /// <remarks/>
        public void GetServiceTypesAsync(SOAConnectionData ConnectionData, object userState) {
            if ((this.GetServiceTypesOperationCompleted == null)) {
                this.GetServiceTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceTypesOperationCompleted);
            }
            this.InvokeAsync("GetServiceTypes", new object[] {
                        ConnectionData}, this.GetServiceTypesOperationCompleted, userState);
        }
        
        private void OnGetServiceTypesOperationCompleted(object arg) {
            if ((this.GetServiceTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceTypesCompleted(this, new GetServiceTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetServiceInfos", RequestElementName="SOAManagerGetServicesInfoRequest", RequestNamespace="http://TotvsSOA.ServiceContracts/v1", ResponseElementName="SOAManagerGetServicesInfoResult", ResponseNamespace="http://TotvsSOA.ServiceContracts/v1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ServicesInfo", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://TotvsSOA.DataContracts/v1")]
        public SOAServiceInfo[] GetServicesInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SOAConnectionData ConnectionData, SOASearchType SearchType, [System.Xml.Serialization.XmlIgnoreAttribute()] bool SearchTypeSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SearchValue) {
            object[] results = this.Invoke("GetServicesInfo", new object[] {
                        ConnectionData,
                        SearchType,
                        SearchTypeSpecified,
                        SearchValue});
            return ((SOAServiceInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetServicesInfoAsync(SOAConnectionData ConnectionData, SOASearchType SearchType, bool SearchTypeSpecified, string SearchValue) {
            this.GetServicesInfoAsync(ConnectionData, SearchType, SearchTypeSpecified, SearchValue, null);
        }
        
        /// <remarks/>
        public void GetServicesInfoAsync(SOAConnectionData ConnectionData, SOASearchType SearchType, bool SearchTypeSpecified, string SearchValue, object userState) {
            if ((this.GetServicesInfoOperationCompleted == null)) {
                this.GetServicesInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServicesInfoOperationCompleted);
            }
            this.InvokeAsync("GetServicesInfo", new object[] {
                        ConnectionData,
                        SearchType,
                        SearchTypeSpecified,
                        SearchValue}, this.GetServicesInfoOperationCompleted, userState);
        }
        
        private void OnGetServicesInfoOperationCompleted(object arg) {
            if ((this.GetServicesInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServicesInfoCompleted(this, new GetServicesInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CreateUser", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void CreateUser([System.Xml.Serialization.XmlElementAttribute(Namespace="http://TotvsSOA.ServiceContracts/v1")] SOAManagerCreateUserRequest SOAManagerCreateUserRequest) {
            this.Invoke("CreateUser", new object[] {
                        SOAManagerCreateUserRequest});
        }
        
        /// <remarks/>
        public void CreateUserAsync(SOAManagerCreateUserRequest SOAManagerCreateUserRequest) {
            this.CreateUserAsync(SOAManagerCreateUserRequest, null);
        }
        
        /// <remarks/>
        public void CreateUserAsync(SOAManagerCreateUserRequest SOAManagerCreateUserRequest, object userState) {
            if ((this.CreateUserOperationCompleted == null)) {
                this.CreateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserOperationCompleted);
            }
            this.InvokeAsync("CreateUser", new object[] {
                        SOAManagerCreateUserRequest}, this.CreateUserOperationCompleted, userState);
        }
        
        private void OnCreateUserOperationCompleted(object arg) {
            if ((this.CreateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ActivateUser", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void ActivateUser([System.Xml.Serialization.XmlElementAttribute(Namespace="http://TotvsSOA.ServiceContracts/v1")] SOAManagerActivateUserRequest SOAManagerActivateUserRequest) {
            this.Invoke("ActivateUser", new object[] {
                        SOAManagerActivateUserRequest});
        }
        
        /// <remarks/>
        public void ActivateUserAsync(SOAManagerActivateUserRequest SOAManagerActivateUserRequest) {
            this.ActivateUserAsync(SOAManagerActivateUserRequest, null);
        }
        
        /// <remarks/>
        public void ActivateUserAsync(SOAManagerActivateUserRequest SOAManagerActivateUserRequest, object userState) {
            if ((this.ActivateUserOperationCompleted == null)) {
                this.ActivateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateUserOperationCompleted);
            }
            this.InvokeAsync("ActivateUser", new object[] {
                        SOAManagerActivateUserRequest}, this.ActivateUserOperationCompleted, userState);
        }
        
        private void OnActivateUserOperationCompleted(object arg) {
            if ((this.ActivateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TotvsSOA.DataContracts/v1")]
    public partial class SOAConnectionData {
        
        private string clientIdField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TotvsSOA.DataContracts/v1")]
    public partial class SOAServiceInfo {
        
        private string serviceTypeField;
        
        private string serviceNameField;
        
        private int serviceVersionField;
        
        private string serviceTitleField;
        
        private string serviceProviderField;
        
        private string serviceDescriptionField;
        
        private string serviceTagsField;
        
        private System.DateTime serviceDateField;
        
        private bool serviceDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
        
        /// <remarks/>
        public int ServiceVersion {
            get {
                return this.serviceVersionField;
            }
            set {
                this.serviceVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceTitle {
            get {
                return this.serviceTitleField;
            }
            set {
                this.serviceTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceProvider {
            get {
                return this.serviceProviderField;
            }
            set {
                this.serviceProviderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceDescription {
            get {
                return this.serviceDescriptionField;
            }
            set {
                this.serviceDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceTags {
            get {
                return this.serviceTagsField;
            }
            set {
                this.serviceTagsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ServiceDate {
            get {
                return this.serviceDateField;
            }
            set {
                this.serviceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceDateSpecified {
            get {
                return this.serviceDateFieldSpecified;
            }
            set {
                this.serviceDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TotvsSOA.DataContracts/v1")]
    public partial class SOADataListItem {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TotvsSOA.DataContracts/v1")]
    public partial class SOAData {
        
        private SOADataKind dataKindField;
        
        private SOADataType dataTypeField;
        
        private string descriptionField;
        
        private string nameField;
        
        private string stateNameField;
        
        private string valueField;
        
        private SOADataListItem[] listItemsField;
        
        private SOAData[] columnsField;
        
        private bool requiredField;
        
        private bool requiredFieldSpecified;
        
        /// <remarks/>
        public SOADataKind DataKind {
            get {
                return this.dataKindField;
            }
            set {
                this.dataKindField = value;
            }
        }
        
        /// <remarks/>
        public SOADataType DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateName {
            get {
                return this.stateNameField;
            }
            set {
                this.stateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SOADataListItem[] ListItems {
            get {
                return this.listItemsField;
            }
            set {
                this.listItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SOAData[] Columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
            }
        }
        
        /// <remarks/>
        public bool Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequiredSpecified {
            get {
                return this.requiredFieldSpecified;
            }
            set {
                this.requiredFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TotvsSOA.Classes")]
    public enum SOADataKind {
        
        /// <remarks/>
        Param,
        
        /// <remarks/>
        Info,
        
        /// <remarks/>
        Result,
        
        /// <remarks/>
        Internal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TotvsSOA.Classes")]
    public enum SOADataType {
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        List,
        
        /// <remarks/>
        Image,
        
        /// <remarks/>
        Table,
        
        /// <remarks/>
        Password,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TotvsSOA.DataContracts/v1")]
    public partial class SOAServiceData {
        
        private string serviceExecutionIdField;
        
        private string serviceTypeField;
        
        private string serviceNameField;
        
        private int serviceVersionField;
        
        private string serviceTitleField;
        
        private string currentStateField;
        
        private string currentStateDescriptionField;
        
        private SOAData[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceExecutionId {
            get {
                return this.serviceExecutionIdField;
            }
            set {
                this.serviceExecutionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
        
        /// <remarks/>
        public int ServiceVersion {
            get {
                return this.serviceVersionField;
            }
            set {
                this.serviceVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceTitle {
            get {
                return this.serviceTitleField;
            }
            set {
                this.serviceTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CurrentState {
            get {
                return this.currentStateField;
            }
            set {
                this.currentStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CurrentStateDescription {
            get {
                return this.currentStateDescriptionField;
            }
            set {
                this.currentStateDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SOAData[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TotvsSOA.Classes")]
    public enum SOAResultType {
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        Finished,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        InvalidParam,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TotvsSOA.Classes")]
    public enum SOASearchType {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        ServiceType,
        
        /// <remarks/>
        ServiceName,
        
        /// <remarks/>
        ServiceTitle,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Provider,
        
        /// <remarks/>
        Tag,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://TotvsSOA.ServiceContracts/v1")]
    public partial class SOAManagerCreateUserRequest {
        
        private string clientIDField;
        
        private string loginField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string companyNameField;
        
        private string eMailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://TotvsSOA.ServiceContracts/v1")]
    public partial class SOAManagerActivateUserRequest {
        
        private string clientIDField;
        
        private string loginField;
        
        private string confirmIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConfirmID {
            get {
                return this.confirmIDField;
            }
            set {
                this.confirmIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ExecuteCompletedEventHandler(object sender, ExecuteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SOAServiceData ServiceData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SOAServiceData)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public SOAResultType ResultType {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SOAResultType)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public bool ResultTypeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string ResultMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public int ResultMessageCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public bool ResultMessageCodeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetServiceCompletedEventHandler(object sender, GetServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SOAServiceData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SOAServiceData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetServiceNamesCompletedEventHandler(object sender, GetServiceNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetServiceTypesCompletedEventHandler(object sender, GetServiceTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetServicesInfoCompletedEventHandler(object sender, GetServicesInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServicesInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServicesInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SOAServiceInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SOAServiceInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CreateUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ActivateUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591