// <auto-generated />
namespace Fly01.Compras.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddServico : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddServico));
        
        string IMigrationMetadata.Id
        {
            get { return "201901101718394_AddServico"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
