// <auto-generated />
namespace Fly01.Financeiro.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ArquivoCamposRequeridos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArquivoCamposRequeridos));
        
        string IMigrationMetadata.Id
        {
            get { return "201711272214018_ArquivoCamposRequeridos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
