// <auto-generated />
namespace Fly01.Financeiro.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlterColumnStatusArquivoRemessa_ArquivoRemessa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterColumnStatusArquivoRemessa_ArquivoRemessa));
        
        string IMigrationMetadata.Id
        {
            get { return "201805181939366_AlterColumnStatusArquivoRemessa_ArquivoRemessa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
