//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Fly01.EmissaoNFE.API.SPEDADMProd {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SPEDADMSOAP", Namespace="http://webservices.totvs.com.br/spedadm.apw")]
    public partial class SPEDADM : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ADDENTFILEOperationCompleted;
        
        private System.Threading.SendOrPostCallback ADMEMISSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ADMEMPRESASOperationCompleted;
        
        private System.Threading.SendOrPostCallback CONSULTEMISSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ENTIDADEATIVAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ENTIDADECLEAROperationCompleted;
        
        private System.Threading.SendOrPostCallback GETADMEMPRESASOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETADMEMPRESASIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETINFOPEDNFEOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETPASSENTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SPEDADM() {
            this.Url = global::Fly01.EmissaoNFE.API.Properties.Settings.Default.Fly01_EmissaoNFE_API_SPEDADMProd_SPEDADM;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ADDENTFILECompletedEventHandler ADDENTFILECompleted;
        
        /// <remarks/>
        public event ADMEMISSCompletedEventHandler ADMEMISSCompleted;
        
        /// <remarks/>
        public event ADMEMPRESASCompletedEventHandler ADMEMPRESASCompleted;
        
        /// <remarks/>
        public event CONSULTEMISSCompletedEventHandler CONSULTEMISSCompleted;
        
        /// <remarks/>
        public event ENTIDADEATIVACompletedEventHandler ENTIDADEATIVACompleted;
        
        /// <remarks/>
        public event ENTIDADECLEARCompletedEventHandler ENTIDADECLEARCompleted;
        
        /// <remarks/>
        public event GETADMEMPRESASCompletedEventHandler GETADMEMPRESASCompleted;
        
        /// <remarks/>
        public event GETADMEMPRESASIDCompletedEventHandler GETADMEMPRESASIDCompleted;
        
        /// <remarks/>
        public event GETINFOPEDNFECompletedEventHandler GETINFOPEDNFECompleted;
        
        /// <remarks/>
        public event GETPASSENTCompletedEventHandler GETPASSENTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.totvs.com.br/spedadm.apw/ADDENTFILE", RequestNamespace="http://webservices.totvs.com.br/spedadm.apw", ResponseElementName="ADDENTFILERESPONSE", ResponseNamespace="http://webservices.totvs.com.br/spedadm.apw", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ADDENTFILERESULT")]
        public string ADDENTFILE(string USERTOKEN, string KEYPASS, string CNPJ, string NOME) {
            object[] results = this.Invoke("ADDENTFILE", new object[] {
                        USERTOKEN,
                        KEYPASS,
                        CNPJ,
                        NOME});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ADDENTFILEAsync(string USERTOKEN, string KEYPASS, string CNPJ, string NOME) {
            this.ADDENTFILEAsync(USERTOKEN, KEYPASS, CNPJ, NOME, null);
        }
        
        /// <remarks/>
        public void ADDENTFILEAsync(string USERTOKEN, string KEYPASS, string CNPJ, string NOME, object userState) {
            if ((this.ADDENTFILEOperationCompleted == null)) {
                this.ADDENTFILEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnADDENTFILEOperationCompleted);
            }
            this.InvokeAsync("ADDENTFILE", new object[] {
                        USERTOKEN,
                        KEYPASS,
                        CNPJ,
                        NOME}, this.ADDENTFILEOperationCompleted, userState);
        }
        
        private void OnADDENTFILEOperationCompleted(object arg) {
            if ((this.ADDENTFILECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ADDENTFILECompleted(this, new ADDENTFILECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.totvs.com.br/spedadm.apw/ADMEMISS", RequestNamespace="http://webservices.totvs.com.br/spedadm.apw", ResponseElementName="ADMEMISSRESPONSE", ResponseNamespace="http://webservices.totvs.com.br/spedadm.apw", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ADMEMISSRESULT")]
        public AUTEMP_EMISSAO ADMEMISS(string USERTOKEN, string ID_ENT, string CNPJ, string CPF, string IE, string UF, [System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string OPC, ARQUIVOAUT ARQUIVO, string PARTNER) {
            object[] results = this.Invoke("ADMEMISS", new object[] {
                        USERTOKEN,
                        ID_ENT,
                        CNPJ,
                        CPF,
                        IE,
                        UF,
                        OPC,
                        ARQUIVO,
                        PARTNER});
            return ((AUTEMP_EMISSAO)(results[0]));
        }
        
        /// <remarks/>
        public void ADMEMISSAsync(string USERTOKEN, string ID_ENT, string CNPJ, string CPF, string IE, string UF, string OPC, ARQUIVOAUT ARQUIVO, string PARTNER) {
            this.ADMEMISSAsync(USERTOKEN, ID_ENT, CNPJ, CPF, IE, UF, OPC, ARQUIVO, PARTNER, null);
        }
        
        /// <remarks/>
        public void ADMEMISSAsync(string USERTOKEN, string ID_ENT, string CNPJ, string CPF, string IE, string UF, string OPC, ARQUIVOAUT ARQUIVO, string PARTNER, object userState) {
            if ((this.ADMEMISSOperationCompleted == null)) {
                this.ADMEMISSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnADMEMISSOperationCompleted);
            }
            this.InvokeAsync("ADMEMISS", new object[] {
                        USERTOKEN,
                        ID_ENT,
                        CNPJ,
                        CPF,
                        IE,
                        UF,
                        OPC,
                        ARQUIVO,
                        PARTNER}, this.ADMEMISSOperationCompleted, userState);
        }
        
        private void OnADMEMISSOperationCompleted(object arg) {
            if ((this.ADMEMISSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ADMEMISSCompleted(this, new ADMEMISSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.totvs.com.br/spedadm.apw/ADMEMPRESAS", RequestNamespace="http://webservices.totvs.com.br/spedadm.apw", ResponseElementName="ADMEMPRESASRESPONSE", ResponseNamespace="http://webservices.totvs.com.br/spedadm.apw", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ADMEMPRESASRESULT")]
        public string ADMEMPRESAS(string USERTOKEN, SPED_ENTIDADE EMPRESA, SPED_ENTIDADEREFERENCIAL OUTRASINSCRICOES) {
            object[] results = this.Invoke("ADMEMPRESAS", new object[] {
                        USERTOKEN,
                        EMPRESA,
                        OUTRASINSCRICOES});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ADMEMPRESASAsync(string USERTOKEN, SPED_ENTIDADE EMPRESA, SPED_ENTIDADEREFERENCIAL OUTRASINSCRICOES) {
            this.ADMEMPRESASAsync(USERTOKEN, EMPRESA, OUTRASINSCRICOES, null);
        }
        
        /// <remarks/>
        public void ADMEMPRESASAsync(string USERTOKEN, SPED_ENTIDADE EMPRESA, SPED_ENTIDADEREFERENCIAL OUTRASINSCRICOES, object userState) {
            if ((this.ADMEMPRESASOperationCompleted == null)) {
                this.ADMEMPRESASOperationCompleted = new System.Threading.SendOrPostCallback(this.OnADMEMPRESASOperationCompleted);
            }
            this.InvokeAsync("ADMEMPRESAS", new object[] {
                        USERTOKEN,
                        EMPRESA,
                        OUTRASINSCRICOES}, this.ADMEMPRESASOperationCompleted, userState);
        }
        
        private void OnADMEMPRESASOperationCompleted(object arg) {
            if ((this.ADMEMPRESASCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ADMEMPRESASCompleted(this, new ADMEMPRESASCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.totvs.com.br/spedadm.apw/CONSULTEMISS", RequestNamespace="http://webservices.totvs.com.br/spedadm.apw", ResponseElementName="CONSULTEMISSRESPONSE", ResponseNamespace="http://webservices.totvs.com.br/spedadm.apw", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("CONSULTEMISSRESULT")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CONTROLENFEEMISS[] CONSULTEMISS(string USERTOKEN, string ID_ENT, string PEDIDO, string IDINICIAL, string IDFINAL) {
            object[] results = this.Invoke("CONSULTEMISS", new object[] {
                        USERTOKEN,
                        ID_ENT,
                        PEDIDO,
                        IDINICIAL,
                        IDFINAL});
            return ((CONTROLENFEEMISS[])(results[0]));
        }
        
        /// <remarks/>
        public void CONSULTEMISSAsync(string USERTOKEN, string ID_ENT, string PEDIDO, string IDINICIAL, string IDFINAL) {
            this.CONSULTEMISSAsync(USERTOKEN, ID_ENT, PEDIDO, IDINICIAL, IDFINAL, null);
        }
        
        /// <remarks/>
        public void CONSULTEMISSAsync(string USERTOKEN, string ID_ENT, string PEDIDO, string IDINICIAL, string IDFINAL, object userState) {
            if ((this.CONSULTEMISSOperationCompleted == null)) {
                this.CONSULTEMISSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCONSULTEMISSOperationCompleted);
            }
            this.InvokeAsync("CONSULTEMISS", new object[] {
                        USERTOKEN,
                        ID_ENT,
                        PEDIDO,
                        IDINICIAL,
                        IDFINAL}, this.CONSULTEMISSOperationCompleted, userState);
        }
        
        private void OnCONSULTEMISSOperationCompleted(object arg) {
            if ((this.CONSULTEMISSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CONSULTEMISSCompleted(this, new CONSULTEMISSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.totvs.com.br/spedadm.apw/ENTIDADEATIVA", RequestNamespace="http://webservices.totvs.com.br/spedadm.apw", ResponseElementName="ENTIDADEATIVARESPONSE", ResponseNamespace="http://webservices.totvs.com.br/spedadm.apw", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ENTIDADEATIVARESULT")]
        public string ENTIDADEATIVA(string USERTOKEN, string ID_ENT, [System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string OPC) {
            object[] results = this.Invoke("ENTIDADEATIVA", new object[] {
                        USERTOKEN,
                        ID_ENT,
                        OPC});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ENTIDADEATIVAAsync(string USERTOKEN, string ID_ENT, string OPC) {
            this.ENTIDADEATIVAAsync(USERTOKEN, ID_ENT, OPC, null);
        }
        
        /// <remarks/>
        public void ENTIDADEATIVAAsync(string USERTOKEN, string ID_ENT, string OPC, object userState) {
            if ((this.ENTIDADEATIVAOperationCompleted == null)) {
                this.ENTIDADEATIVAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnENTIDADEATIVAOperationCompleted);
            }
            this.InvokeAsync("ENTIDADEATIVA", new object[] {
                        USERTOKEN,
                        ID_ENT,
                        OPC}, this.ENTIDADEATIVAOperationCompleted, userState);
        }
        
        private void OnENTIDADEATIVAOperationCompleted(object arg) {
            if ((this.ENTIDADEATIVACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ENTIDADEATIVACompleted(this, new ENTIDADEATIVACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.totvs.com.br/spedadm.apw/ENTIDADECLEAR", RequestNamespace="http://webservices.totvs.com.br/spedadm.apw", ResponseElementName="ENTIDADECLEARRESPONSE", ResponseNamespace="http://webservices.totvs.com.br/spedadm.apw", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ENTIDADECLEARRESULT")]
        public string ENTIDADECLEAR(string USERTOKEN, string ID_ENT) {
            object[] results = this.Invoke("ENTIDADECLEAR", new object[] {
                        USERTOKEN,
                        ID_ENT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ENTIDADECLEARAsync(string USERTOKEN, string ID_ENT) {
            this.ENTIDADECLEARAsync(USERTOKEN, ID_ENT, null);
        }
        
        /// <remarks/>
        public void ENTIDADECLEARAsync(string USERTOKEN, string ID_ENT, object userState) {
            if ((this.ENTIDADECLEAROperationCompleted == null)) {
                this.ENTIDADECLEAROperationCompleted = new System.Threading.SendOrPostCallback(this.OnENTIDADECLEAROperationCompleted);
            }
            this.InvokeAsync("ENTIDADECLEAR", new object[] {
                        USERTOKEN,
                        ID_ENT}, this.ENTIDADECLEAROperationCompleted, userState);
        }
        
        private void OnENTIDADECLEAROperationCompleted(object arg) {
            if ((this.ENTIDADECLEARCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ENTIDADECLEARCompleted(this, new ENTIDADECLEARCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.totvs.com.br/spedadm.apw/GETADMEMPRESAS", RequestNamespace="http://webservices.totvs.com.br/spedadm.apw", ResponseElementName="GETADMEMPRESASRESPONSE", ResponseNamespace="http://webservices.totvs.com.br/spedadm.apw", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GETADMEMPRESASRESULT")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SPED_ENTIDADE[] GETADMEMPRESAS(string USERTOKEN, string CNPJ, string CPF, string IE, string UF, string IDEMPRESA) {
            object[] results = this.Invoke("GETADMEMPRESAS", new object[] {
                        USERTOKEN,
                        CNPJ,
                        CPF,
                        IE,
                        UF,
                        IDEMPRESA});
            return ((SPED_ENTIDADE[])(results[0]));
        }
        
        /// <remarks/>
        public void GETADMEMPRESASAsync(string USERTOKEN, string CNPJ, string CPF, string IE, string UF, string IDEMPRESA) {
            this.GETADMEMPRESASAsync(USERTOKEN, CNPJ, CPF, IE, UF, IDEMPRESA, null);
        }
        
        /// <remarks/>
        public void GETADMEMPRESASAsync(string USERTOKEN, string CNPJ, string CPF, string IE, string UF, string IDEMPRESA, object userState) {
            if ((this.GETADMEMPRESASOperationCompleted == null)) {
                this.GETADMEMPRESASOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETADMEMPRESASOperationCompleted);
            }
            this.InvokeAsync("GETADMEMPRESAS", new object[] {
                        USERTOKEN,
                        CNPJ,
                        CPF,
                        IE,
                        UF,
                        IDEMPRESA}, this.GETADMEMPRESASOperationCompleted, userState);
        }
        
        private void OnGETADMEMPRESASOperationCompleted(object arg) {
            if ((this.GETADMEMPRESASCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETADMEMPRESASCompleted(this, new GETADMEMPRESASCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.totvs.com.br/spedadm.apw/GETADMEMPRESASID", RequestNamespace="http://webservices.totvs.com.br/spedadm.apw", ResponseElementName="GETADMEMPRESASIDRESPONSE", ResponseNamespace="http://webservices.totvs.com.br/spedadm.apw", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GETADMEMPRESASIDRESULT")]
        public string GETADMEMPRESASID(string USERTOKEN, string CNPJ, string CPF, string IE, string UF, string IDEMPRESA) {
            object[] results = this.Invoke("GETADMEMPRESASID", new object[] {
                        USERTOKEN,
                        CNPJ,
                        CPF,
                        IE,
                        UF,
                        IDEMPRESA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETADMEMPRESASIDAsync(string USERTOKEN, string CNPJ, string CPF, string IE, string UF, string IDEMPRESA) {
            this.GETADMEMPRESASIDAsync(USERTOKEN, CNPJ, CPF, IE, UF, IDEMPRESA, null);
        }
        
        /// <remarks/>
        public void GETADMEMPRESASIDAsync(string USERTOKEN, string CNPJ, string CPF, string IE, string UF, string IDEMPRESA, object userState) {
            if ((this.GETADMEMPRESASIDOperationCompleted == null)) {
                this.GETADMEMPRESASIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETADMEMPRESASIDOperationCompleted);
            }
            this.InvokeAsync("GETADMEMPRESASID", new object[] {
                        USERTOKEN,
                        CNPJ,
                        CPF,
                        IE,
                        UF,
                        IDEMPRESA}, this.GETADMEMPRESASIDOperationCompleted, userState);
        }
        
        private void OnGETADMEMPRESASIDOperationCompleted(object arg) {
            if ((this.GETADMEMPRESASIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETADMEMPRESASIDCompleted(this, new GETADMEMPRESASIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.totvs.com.br/spedadm.apw/GETINFOPEDNFE", RequestNamespace="http://webservices.totvs.com.br/spedadm.apw", ResponseElementName="GETINFOPEDNFERESPONSE", ResponseNamespace="http://webservices.totvs.com.br/spedadm.apw", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GETINFOPEDNFERESULT")]
        public PEDIDOSNFE GETINFOPEDNFE(string USERTOKEN, string ID_ENT, string KEYPASS) {
            object[] results = this.Invoke("GETINFOPEDNFE", new object[] {
                        USERTOKEN,
                        ID_ENT,
                        KEYPASS});
            return ((PEDIDOSNFE)(results[0]));
        }
        
        /// <remarks/>
        public void GETINFOPEDNFEAsync(string USERTOKEN, string ID_ENT, string KEYPASS) {
            this.GETINFOPEDNFEAsync(USERTOKEN, ID_ENT, KEYPASS, null);
        }
        
        /// <remarks/>
        public void GETINFOPEDNFEAsync(string USERTOKEN, string ID_ENT, string KEYPASS, object userState) {
            if ((this.GETINFOPEDNFEOperationCompleted == null)) {
                this.GETINFOPEDNFEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETINFOPEDNFEOperationCompleted);
            }
            this.InvokeAsync("GETINFOPEDNFE", new object[] {
                        USERTOKEN,
                        ID_ENT,
                        KEYPASS}, this.GETINFOPEDNFEOperationCompleted, userState);
        }
        
        private void OnGETINFOPEDNFEOperationCompleted(object arg) {
            if ((this.GETINFOPEDNFECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETINFOPEDNFECompleted(this, new GETINFOPEDNFECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.totvs.com.br/spedadm.apw/GETPASSENT", RequestNamespace="http://webservices.totvs.com.br/spedadm.apw", ResponseElementName="GETPASSENTRESPONSE", ResponseNamespace="http://webservices.totvs.com.br/spedadm.apw", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GETPASSENTRESULT")]
        public string GETPASSENT(string USERTOKEN, string ID_ENT, string NEWPASS, [System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string OPC) {
            object[] results = this.Invoke("GETPASSENT", new object[] {
                        USERTOKEN,
                        ID_ENT,
                        NEWPASS,
                        OPC});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETPASSENTAsync(string USERTOKEN, string ID_ENT, string NEWPASS, string OPC) {
            this.GETPASSENTAsync(USERTOKEN, ID_ENT, NEWPASS, OPC, null);
        }
        
        /// <remarks/>
        public void GETPASSENTAsync(string USERTOKEN, string ID_ENT, string NEWPASS, string OPC, object userState) {
            if ((this.GETPASSENTOperationCompleted == null)) {
                this.GETPASSENTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETPASSENTOperationCompleted);
            }
            this.InvokeAsync("GETPASSENT", new object[] {
                        USERTOKEN,
                        ID_ENT,
                        NEWPASS,
                        OPC}, this.GETPASSENTOperationCompleted, userState);
        }
        
        private void OnGETPASSENTOperationCompleted(object arg) {
            if ((this.GETPASSENTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETPASSENTCompleted(this, new GETPASSENTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.totvs.com.br/spedadm.apw")]
    public partial class ARQUIVOAUT {
        
        private string cNPJField;
        
        private string cPFField;
        
        private System.DateTime dATAPEDField;
        
        private string ieField;
        
        private string pEDIDOField;
        
        private string qTDPEDField;
        
        private string ufField;
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DATAPED {
            get {
                return this.dATAPEDField;
            }
            set {
                this.dATAPEDField = value;
            }
        }
        
        /// <remarks/>
        public string IE {
            get {
                return this.ieField;
            }
            set {
                this.ieField = value;
            }
        }
        
        /// <remarks/>
        public string PEDIDO {
            get {
                return this.pEDIDOField;
            }
            set {
                this.pEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string QTDPED {
            get {
                return this.qTDPEDField;
            }
            set {
                this.qTDPEDField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.totvs.com.br/spedadm.apw")]
    public partial class ENTPEDNFE {
        
        private System.DateTime dATAPEDField;
        
        private string nFE_IDField;
        
        private string pEDIDOField;
        
        private string qTDPEDField;
        
        private string sALDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DATAPED {
            get {
                return this.dATAPEDField;
            }
            set {
                this.dATAPEDField = value;
            }
        }
        
        /// <remarks/>
        public string NFE_ID {
            get {
                return this.nFE_IDField;
            }
            set {
                this.nFE_IDField = value;
            }
        }
        
        /// <remarks/>
        public string PEDIDO {
            get {
                return this.pEDIDOField;
            }
            set {
                this.pEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string QTDPED {
            get {
                return this.qTDPEDField;
            }
            set {
                this.qTDPEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string SALDO {
            get {
                return this.sALDOField;
            }
            set {
                this.sALDOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.totvs.com.br/spedadm.apw")]
    public partial class PEDIDOSNFE {
        
        private ENTPEDNFE[] pEDIDOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ENTPEDNFE[] PEDIDOS {
            get {
                return this.pEDIDOSField;
            }
            set {
                this.pEDIDOSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.totvs.com.br/spedadm.apw")]
    public partial class CONTROLENFEEMISS {
        
        private string cNPJDESTField;
        
        private System.DateTime dATE_NFEField;
        
        private string eRROSField;
        
        private string nFE_IDField;
        
        private string pED_DPECField;
        
        private string pED_NFEField;
        
        /// <remarks/>
        public string CNPJDEST {
            get {
                return this.cNPJDESTField;
            }
            set {
                this.cNPJDESTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DATE_NFE {
            get {
                return this.dATE_NFEField;
            }
            set {
                this.dATE_NFEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ERROS {
            get {
                return this.eRROSField;
            }
            set {
                this.eRROSField = value;
            }
        }
        
        /// <remarks/>
        public string NFE_ID {
            get {
                return this.nFE_IDField;
            }
            set {
                this.nFE_IDField = value;
            }
        }
        
        /// <remarks/>
        public string PED_DPEC {
            get {
                return this.pED_DPECField;
            }
            set {
                this.pED_DPECField = value;
            }
        }
        
        /// <remarks/>
        public string PED_NFE {
            get {
                return this.pED_NFEField;
            }
            set {
                this.pED_NFEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.totvs.com.br/spedadm.apw")]
    public partial class SPED_GENERICSTRUCT {
        
        private string cODEField;
        
        private string dESCRIPTIONField;
        
        /// <remarks/>
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.totvs.com.br/spedadm.apw")]
    public partial class SPED_ENTIDADEREFERENCIAL {
        
        private SPED_GENERICSTRUCT[] iNSCRICAOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SPED_GENERICSTRUCT[] INSCRICAO {
            get {
                return this.iNSCRICAOField;
            }
            set {
                this.iNSCRICAOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.totvs.com.br/spedadm.apw")]
    public partial class SPED_ENTIDADE {
        
        private string bAIRROField;
        
        private string cEPField;
        
        private string cEP_CPField;
        
        private string cNPJField;
        
        private string cOD_MUNField;
        
        private string cOD_PAISField;
        
        private string cOMPLField;
        
        private string cpField;
        
        private string cPFField;
        
        private string dDDField;
        
        private System.DateTime dTREField;
        
        private bool dTREFieldSpecified;
        
        private string eMAILField;
        
        private string eNDERECOField;
        
        private string fANTASIAField;
        
        private string fAXField;
        
        private string fONEField;
        
        private string iD_MATRIZField;
        
        private string iDEMPRESAField;
        
        private string ieField;
        
        private string imField;
        
        private string iNDSITESPField;
        
        private string mUNField;
        
        private string nIREField;
        
        private string nITField;
        
        private string nOMEField;
        
        private string nUMField;
        
        private string sUFRAMAField;
        
        private string ufField;
        
        /// <remarks/>
        public string BAIRRO {
            get {
                return this.bAIRROField;
            }
            set {
                this.bAIRROField = value;
            }
        }
        
        /// <remarks/>
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
        
        /// <remarks/>
        public string CEP_CP {
            get {
                return this.cEP_CPField;
            }
            set {
                this.cEP_CPField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        public string COD_MUN {
            get {
                return this.cOD_MUNField;
            }
            set {
                this.cOD_MUNField = value;
            }
        }
        
        /// <remarks/>
        public string COD_PAIS {
            get {
                return this.cOD_PAISField;
            }
            set {
                this.cOD_PAISField = value;
            }
        }
        
        /// <remarks/>
        public string COMPL {
            get {
                return this.cOMPLField;
            }
            set {
                this.cOMPLField = value;
            }
        }
        
        /// <remarks/>
        public string CP {
            get {
                return this.cpField;
            }
            set {
                this.cpField = value;
            }
        }
        
        /// <remarks/>
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        public string DDD {
            get {
                return this.dDDField;
            }
            set {
                this.dDDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DTRE {
            get {
                return this.dTREField;
            }
            set {
                this.dTREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DTRESpecified {
            get {
                return this.dTREFieldSpecified;
            }
            set {
                this.dTREFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        public string ENDERECO {
            get {
                return this.eNDERECOField;
            }
            set {
                this.eNDERECOField = value;
            }
        }
        
        /// <remarks/>
        public string FANTASIA {
            get {
                return this.fANTASIAField;
            }
            set {
                this.fANTASIAField = value;
            }
        }
        
        /// <remarks/>
        public string FAX {
            get {
                return this.fAXField;
            }
            set {
                this.fAXField = value;
            }
        }
        
        /// <remarks/>
        public string FONE {
            get {
                return this.fONEField;
            }
            set {
                this.fONEField = value;
            }
        }
        
        /// <remarks/>
        public string ID_MATRIZ {
            get {
                return this.iD_MATRIZField;
            }
            set {
                this.iD_MATRIZField = value;
            }
        }
        
        /// <remarks/>
        public string IDEMPRESA {
            get {
                return this.iDEMPRESAField;
            }
            set {
                this.iDEMPRESAField = value;
            }
        }
        
        /// <remarks/>
        public string IE {
            get {
                return this.ieField;
            }
            set {
                this.ieField = value;
            }
        }
        
        /// <remarks/>
        public string IM {
            get {
                return this.imField;
            }
            set {
                this.imField = value;
            }
        }
        
        /// <remarks/>
        public string INDSITESP {
            get {
                return this.iNDSITESPField;
            }
            set {
                this.iNDSITESPField = value;
            }
        }
        
        /// <remarks/>
        public string MUN {
            get {
                return this.mUNField;
            }
            set {
                this.mUNField = value;
            }
        }
        
        /// <remarks/>
        public string NIRE {
            get {
                return this.nIREField;
            }
            set {
                this.nIREField = value;
            }
        }
        
        /// <remarks/>
        public string NIT {
            get {
                return this.nITField;
            }
            set {
                this.nITField = value;
            }
        }
        
        /// <remarks/>
        public string NOME {
            get {
                return this.nOMEField;
            }
            set {
                this.nOMEField = value;
            }
        }
        
        /// <remarks/>
        public string NUM {
            get {
                return this.nUMField;
            }
            set {
                this.nUMField = value;
            }
        }
        
        /// <remarks/>
        public string SUFRAMA {
            get {
                return this.sUFRAMAField;
            }
            set {
                this.sUFRAMAField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.totvs.com.br/spedadm.apw")]
    public partial class AUTEMP_EMISSAO {
        
        private string cNPJField;
        
        private string cPFField;
        
        private string iD_ENTField;
        
        private string ieField;
        
        private string qTDEField;
        
        private string sALDOField;
        
        private string ufField;
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        public string ID_ENT {
            get {
                return this.iD_ENTField;
            }
            set {
                this.iD_ENTField = value;
            }
        }
        
        /// <remarks/>
        public string IE {
            get {
                return this.ieField;
            }
            set {
                this.ieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string QTDE {
            get {
                return this.qTDEField;
            }
            set {
                this.qTDEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string SALDO {
            get {
                return this.sALDOField;
            }
            set {
                this.sALDOField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ADDENTFILECompletedEventHandler(object sender, ADDENTFILECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ADDENTFILECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ADDENTFILECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ADMEMISSCompletedEventHandler(object sender, ADMEMISSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ADMEMISSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ADMEMISSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AUTEMP_EMISSAO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AUTEMP_EMISSAO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ADMEMPRESASCompletedEventHandler(object sender, ADMEMPRESASCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ADMEMPRESASCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ADMEMPRESASCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CONSULTEMISSCompletedEventHandler(object sender, CONSULTEMISSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CONSULTEMISSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CONSULTEMISSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CONTROLENFEEMISS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CONTROLENFEEMISS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ENTIDADEATIVACompletedEventHandler(object sender, ENTIDADEATIVACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ENTIDADEATIVACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ENTIDADEATIVACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ENTIDADECLEARCompletedEventHandler(object sender, ENTIDADECLEARCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ENTIDADECLEARCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ENTIDADECLEARCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GETADMEMPRESASCompletedEventHandler(object sender, GETADMEMPRESASCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETADMEMPRESASCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETADMEMPRESASCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SPED_ENTIDADE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SPED_ENTIDADE[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GETADMEMPRESASIDCompletedEventHandler(object sender, GETADMEMPRESASIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETADMEMPRESASIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETADMEMPRESASIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GETINFOPEDNFECompletedEventHandler(object sender, GETINFOPEDNFECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETINFOPEDNFECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETINFOPEDNFECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PEDIDOSNFE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PEDIDOSNFE)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GETPASSENTCompletedEventHandler(object sender, GETPASSENTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETPASSENTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETPASSENTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591