// <auto-generated />
namespace Fly01.Financeiro.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Movimentacao_Conta_Fin_Opcional_Incluir_Categoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Movimentacao_Conta_Fin_Opcional_Incluir_Categoria));
        
        string IMigrationMetadata.Id
        {
            get { return "201711101818399_Movimentacao_Conta_Fin_Opcional_Incluir_Categoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
