using Fly01.Core.Entities.Domains.Commons;
using Fly01.OrdemServico.DAL.Migrations.DataInitializer.Contract;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Fly01.OrdemServico.DAL.Migrations.DataInitializer
{
    public class EnquadramentoLegalIPIDataInitializer : IDataInitializer
    {
        public void Initialize(AppDataContext context)
        {

            if (context.EnquadramentoLegalIPIs.Any())
                return;

            string grupoImunidade = @"Imunidade", grupoSuspensao = @"Suspensão", grupoIsencao = @"Isenção", grupoReducao = @"Redução", grupoOutros = @"Outros";

            context.EnquadramentoLegalIPIs.AddRange(new List<EnquadramentoLegalIPI>()
            {
                #region Imunidade
                    new EnquadramentoLegalIPI() { Id = new Guid("6948c9d6-bbc7-4715-b17c-06a09c4e572f"), Codigo = "001", GrupoCST = grupoImunidade, Descricao = "Livros, jornais, periódicos e o papel destinado à sua impressão - Art. 18 Inciso I do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("d03fbdf5-20af-4114-b4a6-abd31c25fa53"), Codigo = "002", GrupoCST = grupoImunidade, Descricao = "Produtos industrializados destinados ao exterior - Art. 18 Inciso II do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("c7dd04f5-a682-41ae-a41b-ec210b8da8e1"), Codigo = "003", GrupoCST = grupoImunidade, Descricao = "Ouro, definido em lei como ativo financeiro ou instrumento cambial - Art. 18 Inciso III do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("c6975f28-e915-4dae-b4af-8e73d5fae09f"), Codigo = "004", GrupoCST = grupoImunidade, Descricao = "Energia elétrica, derivados de petróleo, combustíveis e minerais do País - Art. 18 Inciso IV do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("cba542a0-a95a-4bdc-b988-3a29c253578a"), Codigo = "005", GrupoCST = grupoImunidade, Descricao = "Exportação de produtos nacionais - sem saída do território brasileiro - venda para empresa sediada no exterior - atividades de pesquisa ou lavra de jazidas de petróleo e de gás natural - Art. 19 Inciso I do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("9d11853b-bc19-4583-9c41-2eb031ef7f4a"), Codigo = "006", GrupoCST = grupoImunidade, Descricao = "Exportação de produtos nacionais - sem saída do território brasileiro - venda para empresa sediada no exterior - incorporados a produto final exportado para o Brasil - Art. 19 Inciso II do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("869a5396-4322-470f-8a1e-211facdeb79b"), Codigo = "007", GrupoCST = grupoImunidade, Descricao = "Exportação de produtos nacionais - sem saída do território brasileiro - venda para órgão ou entidade de governo estrangeiro ou organismo internacional de que o Brasil seja membro, para ser entregue, no País, à ordem do com prador -Art. 19 Inciso III do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    #endregion

                #region Suspensão
                    new EnquadramentoLegalIPI() { Id = new Guid("2046f36f-23bd-4b37-bac7-8af3d0c7391d"), Codigo = "101", GrupoCST = grupoSuspensao, Descricao = "Exportação de produtos nacionais - sem saída do território brasileiro - venda para órgão ou entidade de governo estrangeiro ou organismo internacional de que o Brasil seja membro, para ser entregue, no País, à ordem do com prador -Art. 19 Inciso III do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("66830172-80f0-4d09-a2e9-966a49527cf5"), Codigo = "102", GrupoCST = grupoSuspensao, Descricao = "Produtos remetidos à exposição em feiras de amostras e promoções semelhantes - Art. 43 Inciso II do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("90ba5e84-67ab-45ce-a1e8-f6c97a425900"), Codigo = "103", GrupoCST = grupoSuspensao, Descricao = "Produtos remetidos a depósitos fechados ou arm azéns-gerais, bem assim aqueles devolvidos ao remetente - Art. 43 Inciso III do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("29b189a1-8bf3-4ee8-b115-e6308173bea9"), Codigo = "104", GrupoCST = grupoSuspensao, Descricao = "Produtos industrializados, que com m atérias-prim as (MP), produtos intermediários (PI) e material de embalagem (ME) importados subm etidos a regime aduaneiro especial (drawback - suspensão/isenção), remetidos diretam ente a empresas industriais exportadoras - Art. 43 Inciso IV do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("9e5f0d8c-5073-410b-a5b4-8f36e2edf53f"), Codigo = "105", GrupoCST = grupoSuspensao, Descricao = "Produtos, destinados à exportação, que saiam do estabelecim ento industrial para empresas comerciais exportadoras, com o fim específico de exportação - Art. 43, Inciso V, alínea 'a' do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("5ec036b8-16c6-483b-a069-a918aa112f79"), Codigo = "106", GrupoCST = grupoSuspensao, Descricao = "Produtos, destinados à exportação, que saiam do estabelecim ento industrial para recintos alfandegados onde se processe o despacho aduaneiro de exportação - Art. 43, Inciso V, alíneas 'b' do Decreto 7.212 / 2010 ", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("511f4a39-1193-4c11-a9d4-0bc32538b40a"), Codigo = "107", GrupoCST = grupoSuspensao, Descricao = "Produtos, destinados à exportação, que saiam do estabelecim ento industrial para outros locais onde se processe o despacho aduaneiro de exportação - Art. 43, Inciso V, alíneas 'c' do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("75c258df-e4e6-48fe-a29c-549494390cbe"), Codigo = "108", GrupoCST = grupoSuspensao, Descricao = "Matérias-primas (MP), produtos intermediários (PI) e material de embalagem (ME) destinados ao executor de industrialização por encomenda - Art. 43 Inciso VI do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("7c47ce73-8ba0-49a9-abcc-aaeeef6aa061"), Codigo = "109", GrupoCST = grupoSuspensao, Descricao = "Produtos industrializados por encomenda remetidos ao estabelecim ento de origem - Art. 43 Inciso VII do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("49e9f87c-8074-4506-9808-d5e35dd5fe7a"), Codigo = "110", GrupoCST = grupoSuspensao, Descricao = "Matérias-primas ou produtos intermediários remetidos para emprego em operação industrial realizada pelo remetente fora do estabelecim ento -Art. 43 Inciso VIII do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("26b37611-480d-4fae-9a5b-82c82146253a"), Codigo = "111", GrupoCST = grupoSuspensao, Descricao = "Veículo, aeronave ou embarcação destinados a emprego em provas de engenharia pelo fabricante - Art. 43 Inciso IX do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("ae046549-a238-475d-bfe8-9d8a294e77ee"), Codigo = "112", GrupoCST = grupoSuspensao, Descricao = "Produtos remetidos, para industrialização ou comércio, de um para outro estabelecim ento da mesma firm a - Art. 43 Inciso X do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("401601f7-2e5a-4379-b9f6-b42e80af5dd1"), Codigo = "113", GrupoCST = grupoSuspensao, Descricao = "Bens do ativo permanente remetidos a outro estabelecim ento da mesma firma, para serem utilizados no processo industrial do recebedor - Art. 43 Inciso XI do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("fe223468-d6e9-40bd-a860-321abe87bf7b"), Codigo = "114", GrupoCST = grupoSuspensao, Descricao = "Bens do ativo permanente remetidos a outro estabelecimento, para serem utilizados no processo industrial de produtos encomendados pelo remetente - Art. 43 Inciso XII do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("64da72ca-9f45-49ed-b5f7-7ca859155b14"), Codigo = "115", GrupoCST = grupoSuspensao, Descricao = "Partes e peças destinadas ao reparo de produtos com defeito de fabricação, quando a operação fo r executada gratuitamente, em virtude de garantia - Art. 43 Inciso XIII do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("9199fcd7-90c3-4a4d-8bbb-c1a7e83f8fb9"), Codigo = "116", GrupoCST = grupoSuspensao, Descricao = "Matérias-primas (MP), produtos intermediários (PI) e material de embalagem (ME) de fabricação nacional, vendidos a estabelecim ento industrial, para industrialização de produtos destinados à exportação ou a estabelecim ento comercial, para industrialização em outro estabelecim ento da mesma firm a ou de terceiro, de produto destinado à exportação - Art. 43 Inciso XIV do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("0b93d597-8766-4525-87fe-b65ba8aa2258"), Codigo = "117", GrupoCST = grupoSuspensao, Descricao = "Produtos para emprego ou consumo na industrialização ou elaboração de produto a ser exportado, adquiridos no mercado interno ou importados - Art. 43 Inciso X V do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("0ebb905e-9b16-42bc-9b85-b7c6300aff18"), Codigo = "118", GrupoCST = grupoSuspensao, Descricao = "Bebidas alcóolicas e demais produtos de produção nacional acondicionados em recipientes de capacidade superior ao limite máximo permitido para venda a varejo - Art. 44 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("16f020e1-9678-45e0-a01a-dee3bf4f7580"), Codigo = "119", GrupoCST = grupoSuspensao, Descricao = "Produtos classificados NCM 21.06.90.10 Ex 02, 22.01, 22.02, exceto os Ex 01 e Ex 02 do Código 22.02.90.00 e 22.03 saídos de estabelecim ento industrial destinado a comercial equiparado a industrial - Art. 45 Inciso I do Decreto7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("8f092d16-bdc4-4dcb-8c16-dff2782dc127"), Codigo = "120", GrupoCST = grupoSuspensao, Descricao = "Produtos classificados NCM 21.06.90.10 Ex 02, 22.01, 22.02, exceto os Ex 01 e Ex 02 do Código 22.02.90.00 e 22.03 saídos de estabelecim ento comercial equiparado a industrial destinado a equiparado a industrial - Art. 45 Inciso II do Decreto7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("79dae827-75b1-4e1a-870a-64d516f30405"), Codigo = "121", GrupoCST = grupoSuspensao, Descricao = "Produtos classificados NCM 21.06.90.10 Ex 02, 22.01, 22.02, exceto os Ex 01 e Ex 02 do Código 22.02.90.00 e 22.03 saídos de importador destinado a equiparado a industrial - Art. 45 Inciso III do Decreto7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("0e2ce725-3109-421d-bf18-bdef94d4de0b"), Codigo = "122", GrupoCST = grupoSuspensao, Descricao = "Matérias-primas (MP), produtos intermediários (PI) e material de embalagem (ME) destinados a estabelecim ento que se dedique à elaboração de produtos classificados nos códigos previstos no art. 25 da Lei 10.684/2003 - Art. 46 Inciso I do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("68650c83-debf-4326-b406-038cb7a62ccb"), Codigo = "123", GrupoCST = grupoSuspensao, Descricao = "Matérias-primas (MP), produtos intermediários (PI) e material de embalagem (ME) adquiridos por estabelecim entos industriais fabricantes de partes e peças destinadas a estabelecimento industrial fabricante de produto classificado no Capítulo 88 da Tipi - Art. 46 Inciso II do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("7d793af2-1c9e-4f9d-a336-00cdafa587c4"), Codigo = "124", GrupoCST = grupoSuspensao, Descricao = "Matérias-primas (MP), produtos intermediários (PI) e material de embalagem (ME) adquiridos por pessoas jurídicas preponderantemente exportadoras - Art. 46 Inciso III do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("ef1d4d46-692a-4645-84bb-d04c022efbd4"), Codigo = "125", GrupoCST = grupoSuspensao, Descricao = "Materiais e equipam entos destinados a embarcações pré-registradas ou registradas no Registro Especial Brasileira - REB quando adquiridos por estaleiros navais brasileiros - Art. 46 Inciso IV do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("a3d398ca-c5f0-421f-91a2-c7b572facade"), Codigo = "126", GrupoCST = grupoSuspensao, Descricao = "Aquisição por beneficiário de regime aduaneiro suspensivo do imposto, destinado a industrialização para exportação - Art. 47 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("e8abf099-57c5-4308-95cd-7c1b2370f5b3"), Codigo = "127", GrupoCST = grupoSuspensao, Descricao = "Desembaraço de produtos de procedência estrangeira importados por lojas francas - Art. 48 Inciso I do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("0d8d25e8-f6e9-446d-b785-88bbf1a64045"), Codigo = "128", GrupoCST = grupoSuspensao, Descricao = "Desembaraço de maquinas, equipamentos, veículos, aparelhos e instrumentos sem sim ilar nacional importados por empresas nacionais de engenharia, destinados à execução de obras no exterior - Art. 48 Inciso II do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("429f205f-9373-4f6f-a8db-1ffe6eaf173d"), Codigo = "129", GrupoCST = grupoSuspensao, Descricao = "Desembaraço de produtos de procedência estrangeira com saída de repartições aduaneiras com suspensão do Imposto de Im portação - Art. 48 Inciso III do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("779859d0-e236-45f0-bf44-cbd8377b2325"), Codigo = "130", GrupoCST = grupoSuspensao, Descricao = "Desembaraço de matérias-primas, produtos intermediários e materiais de embalagem, importados diretam ente por estabelecim ento de que tratam os incisos I a III do caput do Decreto 7.212 / 2010 - Art. 48 Inciso IV do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("6c52bff5-582f-402d-9a8d-09b9feaa1522"), Codigo = "131", GrupoCST = grupoSuspensao, Descricao = "Remessa de produtos para a ZFM destinados ao seu consumo interno, utilização ou industrialização - Art. 84 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("c4565371-6f92-4795-9095-5cb422be1495"), Codigo = "132", GrupoCST = grupoSuspensao, Descricao = "Remessa de produtos para a ZFM destinados à exportação - Art. 85 Inciso I do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("e9d4b21d-71a0-45fc-a1eb-ad98f885ad78"), Codigo = "133", GrupoCST = grupoSuspensao, Descricao = "Produtos que, antes de sua remessa à ZFM, forem enviados pelo seu fabricante a outro estabelecimento, para industrialização adicional, por conta e ordem do destinatário - Art. 85 Inciso II do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("906e4631-3752-40f9-b94b-dd3e1d146f10"), Codigo = "134", GrupoCST = grupoSuspensao, Descricao = "Desembaraço de produtos de procedência estrangeira importados pela ZFM quando ali consumidos ou utilizados, exceto armas, munições, fumo, bebidas alcoólicas e automóveis de passageiros. - Art. 86 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("dcd90342-8388-4e46-b1ad-46303651bb92"), Codigo = "135", GrupoCST = grupoSuspensao, Descricao = "Desembaraço de produtos de procedência estrangeira importados pela ZFM quando ali consumidos ou utilizados, exceto armas, munições, fumo, bebidas alcoólicas e automóveis de passageiros. - Art. 86 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("544063e6-d2de-4543-94f6-1116dfc19bb0"), Codigo = "136", GrupoCST = grupoSuspensao, Descricao = "Remessa de produtos para a Am azônia Ocidental destinados ao seu consumo interno ou utilização - Art. 96 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("64e791de-ca1b-464d-9113-27bb60ae3fc4"), Codigo = "137", GrupoCST = grupoSuspensao, Descricao = "Entrada de produtos estrangeiros na Área de Livre Comércio de Guajará-M irim - ALCGM destinados ao seu consumo interno ou utilização - Art. 109 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("790cd31f-2a2c-4af8-8dcc-43aa63d90bcd"), Codigo = "138", GrupoCST = grupoSuspensao, Descricao = "Entrada de produtos estrangeiros nas Áreas de Livre Comércio de Boa Vista - ALCBV e Bomfim - ALCB destinados a seu consumo interno ou utilização - Art. 112 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("aad52c06-82b1-4889-8ca0-4e77ad404478"), Codigo = "139", GrupoCST = grupoSuspensao, Descricao = "Entrada de produtos estrangeiros na Área de Livre Comércio de Macapá e Santana - ALCMS destinados a seu consumo interno ou utilização - Art. 116 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("0816f3fa-628a-40da-aa26-a2180371cd96"), Codigo = "140", GrupoCST = grupoSuspensao, Descricao = "Entrada de produtos estrangeiros nas Áreas de Livre Comércio de Brasiléia - ALCB e de Cruzeiro do Sul - ALCCS destinados a seu consumo interno ou utilização -Art. 119 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("25564897-6291-4308-8ab3-6e52f242a74e"), Codigo = "141", GrupoCST = grupoSuspensao, Descricao = "Remessa para Zona de Processamento de Exportação - ZPE - Art. 121 do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("0842f53d-3e4f-4874-bc3b-b446642a9c1b"), Codigo = "142", GrupoCST = grupoSuspensao, Descricao = "Setor Autom otivo - Desembaraço aduaneiro, chassis e outros - regime aduaneiro especial - industrialização 87.01 a 87.05 - Art. 1 3 6 ,1 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("e2e1183d-8c89-4675-a619-4c075b76dea8"), Codigo = "143", GrupoCST = grupoSuspensao, Descricao = "Setor Autom otivo - Do estabelecim ento industrial produtos 87.01 a 87.05 da TIPI - mercado interno - empresa comercial atacadista controlada por PJ encomendante do exterior. - Art. 136, II do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("8e7ad6df-9b7e-4c99-ba24-6debf5600d96"), Codigo = "144", GrupoCST = grupoSuspensao, Descricao = "Setor Autom otivo - Do estabelecim ento industrial - chassis e outros classificados nas posições 84.29, 84.32, 84.33, 87.01 a 87.06 e 87.11 da TIPI. - Art. 136, III do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("135d48b7-8702-4565-9361-2b2177c5ce64"), Codigo = "145", GrupoCST = grupoSuspensao, Descricao = "Setor Autom otivo - Desembaraço aduaneiro, chassis e outros classificados nas posições 84.29, 84.32, 84.33, 87.01 a 87.06 e 87.11 da TIPI quando importados diretam ente por estabelecim ento industrial - Art. 136, IV do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("5bdb3811-730a-4e7e-9248-4094acb17b23"), Codigo = "146", GrupoCST = grupoSuspensao, Descricao = "Setor Automotivo - do estabelecim ento industrial m atérias-primas, os produtos intermediários e os materiais de embalagem, adquiridos por fabricantes, preponderantemente, de componentes, chassis e outros classificados nos Códigos 84.29, 8432.40.00, 8432.80.00, 8433.20, 8433.30.00, 8433.40.00, 8433.5 e 87.01 a 87.06 da TIPI - Art. 136, V do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("5487d79f-dea6-479f-b8cd-18d9742aeca7"), Codigo = "147", GrupoCST = grupoSuspensao, Descricao = "Setor Autom otivo - Desembaraço aduaneiro, as m atérias-primas, os produtos intermediários e os materiais de embalagem, importados diretam ente por fabricantes, preponderantemente, de componentes, chassis e outros classificados nos Códigos 84.29, 8432.40.00, 8432.80.00, 8433.20, 8433.30.00, 8433.40.00, 8433.5 e 87.01 a 87.06 da TIPI - Art. 136, VI do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("6299af5f-4d48-4494-9a4b-c44db9a7622d"), Codigo = "148", GrupoCST = grupoSuspensao, Descricao = "Bens de Informática e Autom ação - matérias-primas, os produtos intermediários e os materiais de embalagem, quando adquiridos por estabelecim entos industriais fabricantes dos referidos bens. - Art. 148 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("77a4eadb-a47d-48d4-be60-dea5985c4da5"), Codigo = "149", GrupoCST = grupoSuspensao, Descricao = "Reporto - Saída de Estabelecimento de máquinas e outros quando adquiridos por beneficiários do REPORTO - Art. 166, I do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("1d7e2381-3354-4686-9064-47f233c5b0a3"), Codigo = "150", GrupoCST = grupoSuspensao, Descricao = "Reporto - Desembaraço aduaneiro de máquinas e outros quando adquiridos por beneficiários do REPORTO - Art. 166, II do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("53a2e795-e88f-4dbc-bf62-d5fb8702e39a"), Codigo = "151", GrupoCST = grupoSuspensao, Descricao = "Repes - Desembaraço aduaneiro - bens sem sim ilar nacional importados por beneficiários do REPES - Art. 171 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("bafbddf6-ea93-4b95-89ae-8745d6462f0c"), Codigo = "152", GrupoCST = grupoSuspensao, Descricao = "Recine - Saída para beneficiário do regime - Art. 14, III da Lei 12.599/2012", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("3905d3bf-cb05-4367-9ff3-354dd42db26c"), Codigo = "153", GrupoCST = grupoSuspensao, Descricao = "Recine - Desembaraço aduaneiro por beneficiário do regime - Art. 14, IV da Lei 12.599/2012", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("50cb1178-87f3-4a87-a01e-51924e6fd748"), Codigo = "154", GrupoCST = grupoSuspensao, Descricao = "R e if- Saída para beneficiário do regime - Lei 12.794/1013, art. 8, III", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("7f0e2cf7-5c7e-4310-86b5-8a5668c02235"), Codigo = "155", GrupoCST = grupoSuspensao, Descricao = "Reif - Desembaraço aduaneiro por beneficiário do regime - Lei 12.794/1013, art. 8, IV", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("ce07fc92-0cd8-42c3-b523-638707864fd0"), Codigo = "156", GrupoCST = grupoSuspensao, Descricao = "Repnbl-Redes - Saída para beneficiário do regime - Lei n° 12.715/2012, art. 30, II", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("f9b4434a-aacc-4eb0-b666-0281b0835ce4"), Codigo = "157", GrupoCST = grupoSuspensao, Descricao = "Recompe - Saída de m atérias-prim as e produtos intermediários para beneficiários do regime - Decreto n° 7.243/2010, art. 5o, I", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("10d11b05-6483-481b-9ca0-48dc42e88218"), Codigo = "158", GrupoCST = grupoSuspensao, Descricao = "Recompe - Saída de m atérias-prim as e produtos intermediários destinados a industrialização de equipam entos - Program a Estímulo Universidade-Em presa - Apoio à Inovação - Decreto n° 7.243/2010, art. 5o, III", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("50784cc7-66ff-47f8-983c-2b2f421e6d7c"), Codigo = "159", GrupoCST = grupoSuspensao, Descricao = "Rio 2016 - Produtos nacionais, duráveis, uso e consumo dos eventos, adquiridos pelas pessoas jurídicas mencionadas no § 2o do art. 4o da Lei n° 12.780 / 2013 - Lei n° 12.780 / 2013, Art. 13", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("df348146-8784-4140-b047-42c9f9ed461e"), Codigo = "160", GrupoCST = grupoSuspensao, Descricao = "Regime Especial de Adm issão Tem porária nos Term os do Art. 2o da IN 1361/2013", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("90b8e66e-72db-48d5-ae87-9b8c7fa334e8"), Codigo = "161", GrupoCST = grupoSuspensao, Descricao = "Regime Especial de Adm issão Tem porária nos term os do art. 5o da IN 1361/2013", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("19ca88bd-6cbb-4f8c-ba98-14a1048e247c"), Codigo = "162", GrupoCST = grupoSuspensao, Descricao = "Regime Especial de Adm issão Tem porária nos term os do art. 7o da IN 1361/2013 (Suspensão com pagamento de tributos diferidos até a duração do regime, limitado a 100 % do valor original)", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    #endregion

                #region Isenção     
                    new EnquadramentoLegalIPI() { Id = new Guid("b3aa0116-4d6b-4f37-b658-173e4c38452b"), Codigo = "301", GrupoCST = grupoIsencao, Descricao = "Produtos industrializados por instituições de educação ou de assistência social, destinados a uso próprio ou a distribuição gratuita a seus educandos ou assistidos - Art. 54 Inciso I do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("24650803-f0de-467d-a19f-c5fc8fc0d280"), Codigo = "302", GrupoCST = grupoIsencao, Descricao = "Produtos industrializados por estabelecim entos públicos e autárquicos da União, dos Estados, do Distrito Federal e dos Municípios, não destinados a comércio - Art. 54 Inciso II do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("d666a343-87c2-4c3b-8e63-81e03d0aa9af"), Codigo = "303", GrupoCST = grupoIsencao, Descricao = "Am ostras de produtos para distribuição gratuita, de dim inuto ou nenhum valor comercial - Art. 54 Inciso III do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("18abe4f3-2077-439e-ad4b-2c2c5ea9d583"), Codigo = "304", GrupoCST = grupoIsencao, Descricao = "Am ostras de tecidos sem valor comercial - Art. 54 Inciso IV do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("7e669942-204e-4405-9a0c-0bf14ef37a83"), Codigo = "305", GrupoCST = grupoIsencao, Descricao = "Pés isolados de calçados - Art. 54 Inciso V do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("347f0386-e705-43af-b4ba-01658ca58582"), Codigo = "306", GrupoCST = grupoIsencao, Descricao = "Aeronaves de uso militar e suas partes e peças, vendidas à União - Art. 54 Inciso VI do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("36ac642b-6a8d-41eb-9534-c2e5c490588a"), Codigo = "307", GrupoCST = grupoIsencao, Descricao = "Caixões funerários - Art. 54 Inciso VII do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("3157e572-f83b-47b2-9c1c-014e7b880556"), Codigo = "308", GrupoCST = grupoIsencao, Descricao = "Papel destinado à impressão de músicas - Art. 54 Inciso VIII do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("44789922-7a56-4fa4-8a07-9e7059573d3d"), Codigo = "309", GrupoCST = grupoIsencao, Descricao = "Panelas e outros artefatos semelhantes, de uso doméstico, de fabricação rústica, de pedra ou barro bruto - Art. 54 Inciso IX do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("0568c6f3-b579-4c91-acb8-6be2bb827c7e"), Codigo = "310", GrupoCST = grupoIsencao, Descricao = "Chapéus, roupas e proteção, de couro, próprios para tropeiros - Art. 54 Inciso X do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("ed8460a2-8182-4fde-944e-acdc3ae59f7e"), Codigo = "311", GrupoCST = grupoIsencao, Descricao = "Material bélico, de uso privativo das Forças Armadas, vendido à União - Art. 54 Inciso XI do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("f3e77214-26b1-4ce6-a14b-fa10ab12186f"), Codigo = "312", GrupoCST = grupoIsencao, Descricao = "Automóvel adquirido diretam ente a fabricante nacional, pelas missões diplom áticas e repartições consulares de caráter permanente, ou seus integrantes, bem assim pelas representações internacionais ou regionais de que o Brasil seja membro, e seus funcionários, peritos, técnicos e consultores, de nacionalidade estrangeira, que exerçam funções de caráter permanente - Art. 54 Inciso XII do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("30ec9647-a99e-454d-b2fe-2f12f479f56c"), Codigo = "313", GrupoCST = grupoIsencao, Descricao = "Veículo de fabricação nacional adquirido por funcionário das missões diplomáticas acreditadas junto ao Governo Brasileiro - Art. 54 Inciso XIII do Decreto 7.212 / 2010 ", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("4fda8649-a6a8-46a9-8990-5ea2fcf1fa6d"), Codigo = "314", GrupoCST = grupoIsencao, Descricao = "Produtos nacionais saídos diretam ente para Lojas Francas - Art. 54 Inciso XIV do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("b05a40b6-961f-472b-b557-9692d8949b13"), Codigo = "315", GrupoCST = grupoIsencao, Descricao = "Materiais e equipamentos destinados a Itaipu Binacional - Art. 54 Inciso X V do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("f7d6213d-f52a-4d3d-892d-fe1e0eee4f5c"), Codigo = "316", GrupoCST = grupoIsencao, Descricao = "Produtos Importados por missões diplomáticas, consulados ou organism o internacional - Art. 54 Inciso XVI do Decreto 7.212 / 2010 ", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("951dde67-9778-4feb-8c65-4a7547cb1008"), Codigo = "317", GrupoCST = grupoIsencao, Descricao = "Bagagem de passageiros desembaraçada com isenção do II. - Art. 54 Inciso XVII do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("24ef64d3-0e21-4cfd-8b21-93abe7857c18"), Codigo = "318", GrupoCST = grupoIsencao, Descricao = "Bagagem de passageiros desembaraçada com pagamento do II. - Art. 54 Inciso XVIII do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("bf71c3e7-ec36-494f-9ed8-bb7830141fec"), Codigo = "319", GrupoCST = grupoIsencao, Descricao = "Remessas postais internacionais sujeitas a tributação simplificada. - Art. 54 Inciso XIX do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("4eba5f6b-9b6f-48eb-b2b4-e712b6598876"), Codigo = "320", GrupoCST = grupoIsencao, Descricao = "Máquinas e outros destinados à pesquisa científica e tecnológica - Art. 54 Inciso XX do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("2b5222ad-669c-41c3-b092-89bb46c5faae"), Codigo = "321", GrupoCST = grupoIsencao, Descricao = "Produtos de procedência estrangeira, isentos do II conform e Lei n° 8032/1990. - Art. 54 Inciso XXI do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("aab1a8a3-bf4b-4402-b528-545d45bb799c"), Codigo = "322", GrupoCST = grupoIsencao, Descricao = "Produtos de procedência estrangeira utilizados em eventos esportivos - Art. 54 Inciso XXII do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("901fd450-9814-4279-9013-34a2d7d0f13f"), Codigo = "323", GrupoCST = grupoIsencao, Descricao = "Veículos automotores, máquinas, equipamentos, bem assim suas partes e peças separadas, destinadas à utilização nas atividades dos Corpos de Bombeiros - Art. 54 Inciso XXIII do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("ff4423ac-60f8-4d84-b95d-2d496f8b136d"), Codigo = "324", GrupoCST = grupoIsencao, Descricao = "Produtos importados para consumo em congressos, feiras e exposições - Art. 54 Inciso XXIV do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("34b2b2fc-faf7-4a4a-90e6-ef8b1483e266"), Codigo = "325", GrupoCST = grupoIsencao, Descricao = "Bens de informática, Matéria Prima, produtos intermediários e embalagem destinados a Urnas eletrônicas - TSE - Art. 54 Inciso XXV do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("6c1ed4a5-06dc-4602-a2e1-51198c4592a4"), Codigo = "326", GrupoCST = grupoIsencao, Descricao = "Materiais, equipamentos, máquinas, aparelhos e instrumentos, bem assim os respectivos acessórios, sobressalentes e ferramentas, que os acom panhem , destinados à construção do Gasoduto Brasil -Bolívia - Art. 54 Inciso )0 < VI do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("43e36d9c-7c64-478b-804f-a5ab7c6ec9aa"), Codigo = "327", GrupoCST = grupoIsencao, Descricao = "Partes, peças e componentes, adquiridos por estaleiros navais brasileiros, destinados ao emprego na conservação, modernização, conversão ou reparo de embarcações registradas no Registro Especial Brasileiro - REB - Art. 54 Inciso XXVII do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("794eebde-94f4-4c11-8463-f5513a30343f"), Codigo = "328", GrupoCST = grupoIsencao, Descricao = "Aparelhos transm issores e receptores de radiotelefonia e radiotelegrafia; veículos para patrulhamento policial; arm as e munições, destinados a órgãos de segurança pública da União, dos Estados e do Distrito Federal -Art. 54 Inciso XXVIII do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("b6f50882-4739-43c6-82b4-edda0c5e2f11"), Codigo = "329", GrupoCST = grupoIsencao, Descricao = "Automóveis de passageiros de fabricação nacional destinados à utilização como táxi adquiridos por m otoristas profissionais - Art. 55 Inciso I do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("0cfc1ad5-37f5-4a24-9e9f-d1f6ac4cb546"), Codigo = "330", GrupoCST = grupoIsencao, Descricao = "Automóveis de passageiros de fabricação nacional destinados à utilização como táxi por impedidos de exercer atividade por destruição, furto ou roubo do veículo adquiridos por motoristas profissionais. - Art. 55 Inciso II do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("af106050-b790-4090-8278-66e2e759e2e4"), Codigo = "331", GrupoCST = grupoIsencao, Descricao = "Automóveis de passageiros de fabricação nacional destinados à utilização como táxi adquiridos por cooperativas de trabalho. - Art. 55 Inciso II do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("0c284b35-f8c7-431d-9be0-30edf82974c1"), Codigo = "332", GrupoCST = grupoIsencao, Descricao = "Automóveis de passageiros de fabricação nacional, destinados a pessoas portadoras de deficiência física, visual, mental severa ou profunda, ou autistas - Art. 55 Inciso IV do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("93902393-c9ff-4faf-9081-ab0c6a48b9a7"), Codigo = "333", GrupoCST = grupoIsencao, Descricao = "Produtos estrangeiros, recebidos em doação de representações diplom áticas estrangeiras sediadas no País, vendidos em feiras, bazares e eventos sem elhantes por entidades beneficentes - Art. 67 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("8810e4c5-4193-4148-8cae-1f0f2e05e28d"), Codigo = "334", GrupoCST = grupoIsencao, Descricao = "Produtos industrializados na Zona Franca de Manaus - ZFM, destinados ao seu consumo interno - Art. 81 Inciso I do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("f4a99fbc-e00c-4d60-ae3d-628ca5c88fae"), Codigo = "335", GrupoCST = grupoIsencao, Descricao = "Produtos industrializados na ZFM, por estabelecim entos com projetos aprovados pela SUFRAMA, destinados a comercialização em qualquer outro ponto do Território Nacional - Art. 81 Inciso II do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("7535fb72-8f2c-4985-8046-c235f30178f3"), Codigo = "336", GrupoCST = grupoIsencao, Descricao = "Produtos nacionais destinados à entrada na ZFM, para seu consumo interno, utilização ou industrialização, ou ainda, para serem remetidos, por intermédio de seus entrepostos, à Am azônia Ocidental - Art. 81 Inciso III do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("8122ffd8-6282-4f41-ba46-e094c7ea935b"), Codigo = "337", GrupoCST = grupoIsencao, Descricao = "Produtos industrializados por estabelecim entos com projetos aprovados pela SUFRAMA, consumidos ou utilizados na Am azônia Ocidental, ou adquiridos através da ZFM ou de seus entrepostos na referida região - Art. 95 Inciso I do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("db30e1c5-af56-4530-bba0-f61ef97e6f72"), Codigo = "338", GrupoCST = grupoIsencao, Descricao = "Produtos de procedência estrangeira, relacionados na legislação, oriundos da ZFM e que derem entrada na Am azônia Ocidental para ali serem consumidos ou utilizados: - Art. 95 Inciso II do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("2959bade-6e1f-4d9a-8934-6307c07c7d98"), Codigo = "339", GrupoCST = grupoIsencao, Descricao = "Produtos elaborados com m atérias-prim as agrícolas e extrativas vegetais de produção regional, por estabelecim entos industriais localizados na Am azônia Ocidental, com projetos aprovados pela SUFRAM A - Art. 95 Inciso III do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("a840bbd3-cd40-4683-ae33-5b2fd0011cf8"), Codigo = "340", GrupoCST = grupoIsencao, Descricao = "Produtos industrializados em Área de Livre Comércio - Art. 105 do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("8a9aba18-a84b-4b27-a072-a0ec425343fc"), Codigo = "341", GrupoCST = grupoIsencao, Descricao = "Produtos nacionais ou nacionalizados, destinados à entrada na Área de Livre Comércio de Tabatinga - ALCT - Art. 107 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("8822b961-5b3b-4629-8711-813a451aed02"), Codigo = "342", GrupoCST = grupoIsencao, Descricao = "Produtos nacionais ou nacionalizados, destinados à entrada na Área de Livre Comércio de Guaiará-Mirim - ALCGM - Art. 110 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("830d6371-a58c-40dd-9521-fce67100f7ec"), Codigo = "343", GrupoCST = grupoIsencao, Descricao = "Produtos nacionais ou nacionalizados, destinados à entrada nas Áreas de Livre Comércio de Boa Vista - ALC BV e Bonfim - ALCB - Art. 113 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("3b2feac6-766d-4840-a1a2-a9ad1f51c8e4"), Codigo = "344", GrupoCST = grupoIsencao, Descricao = "Produtos nacionais ou nacionalizados, destinados à entrada na Área de Livre Comércio de Macapá e Santana - ALCM S - Art. 117 do Decreto 7.212 / 2010 ", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("b41b109f-c02c-409f-b551-92eeed30334c"), Codigo = "345", GrupoCST = grupoIsencao, Descricao = "Produtos nacionais ou nacionalizados, destinados à entrada nas Áreas de Livre Comércio de Brasiléia - ALCB e de Cruzeiro do Sul - ALCCS - Art. 120 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("4043eb3c-59cd-4fdb-9f67-cae2e9e3c89e"), Codigo = "346", GrupoCST = grupoIsencao, Descricao = "Recompe - equipam entos de informática - de beneficiário do regime para escolas das redes públicas de ensino federal, estadual, distrital, municipal ou nas escolas sem fins lucrativos de atendim ento a pessoas com deficiência - Decreto n° 7.243/2010, art. 7o", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("3741a600-c63f-4329-ab7d-10c5f259b835"), Codigo = "347", GrupoCST = grupoIsencao, Descricao = "Rio 2016 - Importação de materiais para os jogos (medalhas, troféus, impressos, bens não duráveis, etc.) - Lei n° 12.780 / 2013, Art. 4o, §1°, I", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("9390d714-f3c0-4222-9eab-1144c117a926"), Codigo = "348", GrupoCST = grupoIsencao, Descricao = "Rio 2016 - Suspensão convertida em Isenção - Lei n° 12.780/2013, Art. 6o, I", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("007de45d-5261-45d5-94dd-eb581c3b64fe"), Codigo = "349", GrupoCST = grupoIsencao, Descricao = "Rio 2016 - Empresas vinculadas ao CIO - Lei n° 12.780/2013, Art. 9o, I, d", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("b6213ad1-e77b-491e-85e4-55d9c6151ba7"), Codigo = "350", GrupoCST = grupoIsencao, Descricao = "Rio 2016 - Saída de produtos importados pelo RIO 2016 - Lei n° 12.780/2013, Art. 10, I, d", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("4810c4a3-63a5-40c5-ad17-9328dfa8652c"), Codigo = "351", GrupoCST = grupoIsencao, Descricao = "Rio 2016 - Produtos nacionais, não duráveis, uso e consum o dos eventos, adquiridos pelas pessoas jurídicas mencionadas no § 2o do art. 4o da Lei n° 12.780 / 2013 - Lei n° 12.780 / 2013, Art. 12", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    #endregion

                #region Redução
                    new EnquadramentoLegalIPI() { Id = new Guid("1acaa58a-5857-4aca-a60c-e904a9236d80"), Codigo = "601", GrupoCST = grupoReducao, Descricao = "Equipamentos e outros destinados à pesquisa e ao desenvolvim ento tecnológico - Art. 72 do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("d86c8af1-a84a-4585-a7a4-50bf516058e2"), Codigo = "602", GrupoCST = grupoReducao, Descricao = "Equipamentos e outros destinados à empresas habilitadas no PDTI e PDTA utilizados em pesquisa e ao desenvolvim ento tecnológico - Art. 73 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("5b553e67-2920-4c69-a6c3-3c7e25807b76"), Codigo = "603", GrupoCST = grupoReducao, Descricao = "Microcomputadores e outros de até R$11.000,00, unidades de disco, circuitos, etc, destinados a bens de informática ou automação. Centro-Oeste SUDAM SUDENE - Art. 142, I do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("2da18c36-5eea-4d81-af08-93f1b4991272"), Codigo = "604", GrupoCST = grupoReducao, Descricao = "Microcomputadores e outros de até R$11.000,00, unidades de disco, circuitos, etc, destinados a bens de informática ou automação. - Art. 1 4 2 ,1 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("07368a79-3db4-403d-bd58-2c15a95cad65"), Codigo = "605", GrupoCST = grupoReducao, Descricao = "Bens de informática não incluídos no art. 142 do Decreto 7.212/2010 - Produzidos no CentroOeste, SUDAM, SUDENE - Art. 1 4 3 ,1 do Decreto 7.212 / 2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("2eec559b-7309-44af-bf75-66a7b0d7c33c"), Codigo = "606", GrupoCST = grupoReducao, Descricao = "Bens de informática não incluídos no art. 142 do Decreto 7.212/2010 - Art. 143, II do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("888dffcd-85a7-4fe7-951a-0827c22ed1fa"), Codigo = "607", GrupoCST = grupoReducao, Descricao = "Padis - Art. 150 do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    new EnquadramentoLegalIPI() { Id = new Guid("39f2816d-d211-4aaf-96db-6eb55fd13fc0"), Codigo = "608", GrupoCST = grupoReducao, Descricao = "Patvd - Art. 158 do Decreto 7.212/2010", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    #endregion

                #region Outros
                    new EnquadramentoLegalIPI() { Id = new Guid("34bb3258-6133-4a74-8b05-f6cb512e9833"), Codigo = "999", GrupoCST = grupoOutros, Descricao = "Tributação normal IPI; Outros;", DataInclusao = DateTime.Now, UsuarioInclusao = "SEED", Ativo = true },
                    #endregion
            });

            context.SaveChanges();
        }
    }
}
