// <auto-generated />
namespace Fly01.Estoque.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterMovimento_OptionalTipoMovimentoId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterMovimento_OptionalTipoMovimentoId));
        
        string IMigrationMetadata.Id
        {
            get { return "201801082058240_AlterMovimento_OptionalTipoMovimentoId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
