// <auto-generated />
namespace Fly01.EmissaoNFE.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_TabelaIcms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_TabelaIcms));
        
        string IMigrationMetadata.Id
        {
            get { return "201802011725312_Create_TabelaIcms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
