// <auto-generated />
namespace Fly01.EmissaoNFE.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_CFOP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_CFOP));
        
        string IMigrationMetadata.Id
        {
            get { return "201803141911441_Create_CFOP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
