// <auto-generated />
namespace Fly01.EmissaoNFE.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InsertIBPT_DF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertIBPT_DF));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281325236_InsertIBPT_DF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
